### ISSUE TITLE
Empty MYSQL login details

### ISSUE THREAD

**Issue by nalimleinad** [games647/FlexibleLogin#1]
I have filled config user and password, but It looks like empty during startup so I cannot connect to database.

My config:
http://pastebin.com/YhGmsEeg

FML log:
http://pastebin.com/rMieAHCw

Error starts on line 1195

**Comment by games647** [comment]
Does a database with the name "flexiblelogin" exist?

**Comment by nalimleinad** [comment]
Yes, database exist.

**Comment by games647** [comment]
Should be fixed now. I found also a bug in the MySQL driver and worked around it.

**Comment by nalimleinad** [comment]
Works for now. Thanks you!
