### ISSUE TITLE
ResetPW Command does not work

### ISSUE THREAD

**Issue by GershonR** [games647/FlexibleLogin#101]
I'm using 0.16.5 Flexible Login with the case sensitive name checking turned off and I cannot reset/change passwords, I tried doing it when they are online and offline, it says the password has been changed but when they use the new password it does not log them in.

spongeforge-1.12.2-2611-7.1.0-BETA-2916

**Comment by games647** [comment]
Do you have any errors in the logs?

**Comment by GershonR** [comment]
I do not get any errors it just says password has been changed

**Comment by games647** [comment]
Do you used the UUID or the name version of the reset command?

**Comment by GershonR** [comment]
I use player names, i.e /flexiblelogin resetpw bob test, when I was using the API 5 /flexiblelogin changepassword it was working fine for me

**Comment by GershonR** [comment]
It works, thanks for the quick fix
