### ISSUE TITLE
MySQL / MariaDB

### ISSUE THREAD

**Issue by fmohican** [games647/FlexibleLogin#104]
Hi!
I use your plugin on my server, i setup mariadb, but the plugin isn't use...
There its console error and the config
https://gist.github.com/fmohican/af6bb4eb435b41140f7ae15f0e4ede3b

**Comment by games647** [comment]
Just put MySQL in there. MariaDB is backwards compatible to MySQL

**Comment by fmohican** [comment]
Yes i know that, but you in config but separately MariaDB & MySQL, i will change to mysql and i will reply you back.

**Comment by games647** [comment]
That comment will be fixed in the next version to make it more clear.

**Comment by fmohican** [comment]
Now workfine
but why UUID and IP are stored as Binary Data ?

**Comment by games647** [comment]
The thought was that this is smaller and so reduces the size of the database and improve performance of indices.

For example UUIDs only have a width of 2 * 64 bits (long) = 128 bits. If you store it as a fixed string the size would be 36 (UUID without dashes) * 16 bits (UTF-8) = 576 bits, but now I think it's unnecessary.

**Comment by fmohican** [comment]
Well thanks you for making clear about mySQL / mariadb. Thanks for support.
