### ISSUE TITLE
hashing passwords

### ISSUE THREAD

**Issue by wallxq** [games647/FlexibleLogin#105]
How i can off hashing user passwords and IP?

**Comment by games647** [comment]
What do you mean? You want to hash the passwords in another programming language like PHP?

**Comment by wallxq** [comment]
I want hash in md5 or i want without hash for can look passwords users. Its important for me because i cant get values password on my website for login.

**Comment by games647** [comment]
See #100 for my opinion on MD5. (TL;DR FlexibleLogin and PHP supports BCrypt by default which is much stronger)

**Comment by wallxq** [comment]
Okay, thanks you:)
