### ISSUE TITLE
bug sqlite with /register

### ISSUE THREAD

**Issue by ternsip** [games647/FlexibleLogin#106]
Unparseable date: "2018-03-01 19:22:35" does not match (\p{Nd}++)\Q-\E(\p{Nd}++)\Q-\E(\p{Nd}++)\Q \E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q.\E(\p{Nd}++)
[link](https://gist.github.com/ternsip/85e3b251522a2a0bc4309c89aedba6f5)

**Comment by games647** [comment]
It's crazy that SQLite still has this bug. Sadly Sponge doesn't provide a way to set custom database connector settings. Could you switch to H2, it doesn't seem to have that issue.

**Comment by FromZeus** [comment]
@games647 Okay, thank you for quick response! We'll use mysql then :)
