### ISSUE TITLE
Add Copyright on all source code files

### ISSUE THREAD

**Issue by frogocomics** [games647/FlexibleLogin#11]
(See title)

**Comment by games647** [comment]
Something like that isn't required.

**Comment by frogocomics** [comment]
Its usually convention- if you use Intelljidea, there is an option to add a license header to all the java source files at once- of course, I could do that, if you want.

**Comment by games647** [comment]
>if you use Intelljidea

As far as I know all IDEs including a maven plugin have this option. 

>I could do that, if you want.

That would be great. I'm very busy with other projects at the moment.

>Its usually convention

I thought It's not really needed especially if you use an open license like MIT.
