### ISSUE TITLE
Sponge API 8

### ISSUE THREAD

**Issue by fmohican** [games647/FlexibleLogin#110]
Does support Sponge API 8 ?

https://files.minecraftforge.net/maven/org/spongepowered/spongeforge/index_1.12.2.html 
8.0.0-BETA-2954

**Comment by games647** [comment]
I tried to compile it with Sponge 8 and ran quick test. Everything seems to work fine, but maybe you want to make a custom test server with your specific configuration to make sure.

**Comment by fmohican** [comment]
Thanks you.
