### ISSUE TITLE
NEIJ/JEI buttons without login

### ISSUE THREAD

**Issue by ternsip** [games647/FlexibleLogin#111]
If I left the game in creative mod then someone who join can double-space to creative-fly strait up (and falldown) without /login command.
If i have admin rights I can change time of a day and rain using NEI/JEI buttons (without login)

**Comment by games647** [comment]
>NEI/JEI buttons (without login)

Is that a mod?

>If I left the game in creative mod then someone who join can double-space to creative-fly strait up (and falldown) without /login command.

Is that really an issue for you? I thought we can ignore it.

**Comment by ternsip** [comment]
NEI/JEI is a forge mod for minecraft. Looks like:
![image](https://user-images.githubusercontent.com/10179239/37254196-fa861fbe-254b-11e8-8432-9fbe866a7b40.png)
It's very popular mod.
Yes it is because players can cheat throgh it if they playing in offline mod with auth in-game.

**Comment by games647** [comment]
>Yes it is because players can cheat throgh it if they playing in offline mod with auth in-game.

If you can only move in y direction how is that cheating?

**Comment by ternsip** [comment]
No, you can change weather etc. upper-left buttons.

**Comment by games647** [comment]
Yes but I was quoting the movement part.

**Comment by ternsip** [comment]
Movement is not so badly, like time of a day. Yes, you are right about vertical movement.

**Comment by games647** [comment]
Are you OP on your server. Then it could be a solution to temporarily remove the OP status.

**Comment by ternsip** [comment]
That means - all server with that mod where ops was in the world, i can cheat using their accounts.

**Comment by games647** [comment]
Does that mean yes you ware OP?

**Comment by ternsip** [comment]
Yeas, Iam OP on my server. But i'm not only one. And there is very problematic to do remove it all the time using lucky perms when I quit. But your mod is fine. I have a few questions? 
Clients can fill theyr passowrd in menu gui.
Can you kick players when they join the game with incorrect password if they registered. And register if there is no such player with such name on the server with provided password?
I tried by myself to kick player on player-login event and I could not send packets on this stage for handshake.

**Comment by games647** [comment]
>Clients can fill theyr passowrd in menu gui.

Yes it's possible, but not implemented in this plugin, because this should work on vanilla servers too.

>Can you kick players when they join the game with incorrect password if they registered

No it's possible, they have to join the server first.

>I tried by myself to kick player on player-login event and I could not send packets on this stage for handshake.

There are no kick packets at this stage. You have to send disconnect packets. This is basically the response from a join event.

**Comment by ternsip** [comment]
Biggest problem I can't solve is how to make a handshake before player joins the game (the stage he can change weather move etc)

**Comment by games647** [comment]
you mean login (not joining the game/server)?

**Comment by ternsip** [comment]
Yeah, how to send packets from client to server and back a few times to make a handshake to determine it is required to kick or stay.

**Comment by games647** [comment]
Sorry, but I don't have experience with Forge modding.

**Comment by ternsip** [comment]
Is it possible over sponge?

**Comment by games647** [comment]
Sponge has no implementation for custom packets, but you could use Plugin Message for communicating between client and server.

**Comment by ternsip** [comment]
Please, can you fix it? or wont fix, or its already fixed in some commit or release?

**Comment by games647** [comment]
It's already fixed in an experimental commit. You can download it from here: https://ci.codemc.org/job/Games647/job/FlexibleLogin/

**Comment by ternsip** [comment]
![image](https://user-images.githubusercontent.com/10179239/37257605-ef5af430-257c-11e8-9a36-d395632621b5.png)
flexiblelogin-0.17.jar
