### ISSUE TITLE
[API7]could not login!

### ISSUE THREAD

**Issue by Tollainmear** [games647/FlexibleLogin#112]
while I join to the server and type /login command(after regist registration), I was noticed that 'You entered too many times a wrong password'.

Test with FlexableLogin version 0.17
minecraft: 1.12.2
Sponge api : 7.1.0-6aa4e43
Spongeforge: 1.12.2-2611-7.1.0-Beta-2931
minecraftForge: 14.23.2.2611

**Comment by ziceptor** [comment]
The player register out perfectly. But after exit not can to join.

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar
flexiblelogin-0.17.jar

For the test. I deleted the database and configuration files. It doesn't help.

**Comment by Tollainmear** [comment]
Thx for update~!
