### ISSUE TITLE
How about extract the message file in to the resource pack

### ISSUE THREAD

**Issue by Tollainmear** [games647/FlexibleLogin#113]
Then I could help you to translate the language file into Chinese with a simple pullrequest.

**Comment by games647** [comment]
Great idea, but the text file is generated automatically. With the current setup in integrates well with the code without having any duplication. 

An alternative could be to write a wiki page about already translated language files here: 
https://github.com/games647/FlexibleLogin/wiki

**Comment by Tollainmear** [comment]
Fine, but not `Flexible` enough right? XD

**Comment by Tollainmear** [comment]
[local.conf in wiki](https://github.com/games647/FlexibleLogin/wiki/%E4%B8%AD%E6%96%87%EF%BC%88Chinese%EF%BC%89)

**Comment by games647** [comment]
Thank you very much. I'll add a link to the ReadMe and locale file.

**Comment by Tollainmear** [comment]
Hi~ I find another thing may not correct, the `lastOnline` and `notRegistered`’s comment looks like wrong in locale.conf( emmmm Is that should be named local.conf `XD`)
That was not a serious problem, just founded while I back to finish the remaining comment. so I think it may not needed to create a new issue~ `_(:з」∠)_`
@games647
