### ISSUE TITLE
Login with Bcrypt Algorithm not working

### ISSUE THREAD

**Issue by pdglobal** [games647/FlexibleLogin#116]
When I try to login with the bcrypt hashing algorithm via the authme schema I get the following error in console. (see attached photo)
![image](https://user-images.githubusercontent.com/36902779/37380357-b1919ae4-270e-11e8-8227-c5d26d22c767.png)

**Comment by pdglobal** [comment]
Note: I am using the latest source code as of 3/13/18 9:00pm EST. (compiled directly from git)

**Comment by games647** [comment]
Do you correctly compiled it with Maven, because I don't see the relocation to flexible.bcrypt?

**Comment by pdglobal** [comment]
Okay, I got it compiled correctly using maven now, and it's preventing me from moving/executing commands, but now I get THIS error on joining the server and it still says I'm not registered
![image](https://user-images.githubusercontent.com/36902779/37397692-9b78f470-2752-11e8-8c10-75160482d623.png)
