### ISSUE TITLE
Mod flexiblelogin (FlexibleLogin) requires [griefprevention@[4.0.1,)]

### ISSUE THREAD

**Issue by BadassOverlord** [games647/FlexibleLogin#123]
Plugin does not work with the latest version of griefprevention for 1.12.2, which is 4.3.0.

The error I get is: 
net.minecraftforge.fml.common.MissingModsException: Mod flexiblelogin (FlexibleLogin) requires [griefprevention@[4.0.1,)]

**Comment by games647** [comment]
According to the [Sponge documentation](https://github.com/SpongePowered/SpongeAPI/blob/ef8aa4f8288f2565ef306e00567eab39e9485923/src/main/java/org/spongepowered/api/plugin/Dependency.java#L56).

>     * <tr><td>[1.0,)</td><td>x >= 1.0</td></tr>

[4.0.1,) means any version greater than 4.0.1

**Comment by BadassOverlord** [comment]
Yeah but it causes the server to crash and doesn't boot up, so I guess it's not working.

**Comment by games647** [comment]
What Sponge version do you run? Maybe it helps to upgrade or downgrade.

**Comment by BadassOverlord** [comment]
Spongeforge 1.12.2-2611-7.1.0-BETA-2970

Downgrading is unfortunately not a possibility as the minimum forge version requirement for some of the mods in this modpack is 2611.

**Comment by games647** [comment]
No only downgrade SpongeForge (not forge) to something like 2960, 2977 ...

**Comment by BadassOverlord** [comment]
I tried 2977 and 2958 and neither of them worked :(

**Comment by BadassOverlord** [comment]
Apologies for not posting the complete error. Here is the full error:

`
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (forge-1.12.2-14.23.2.2611-universal.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-63.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  FMLPlugin (elulib-0.1.12.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.2.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-77-core.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-79-core.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.5.2.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 3/23/18 12:25 PM
Description: Exception in server tick loop

Missing Mods:
	griefprevention : [4.0.1,)

net.minecraftforge.fml.common.MissingModsException: Mod flexiblelogin (FlexibleLogin) requires [griefprevention@[4.0.1,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:278)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:545)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:278)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:545)

-- Sponge PhaseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjf000(MinecraftServer.java:4013)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:556)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 565529176 bytes (539 MB) / 1818755072 bytes (1734 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xmx4G -XX:MaxPermSize=256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 186 mods loaded, 186 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                  | Source                                            | Signature                                |
	|:----- |:------------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| U     | minecraft                 | 1.12.2                   | minecraft.jar                                     | None                                     |
	| U     | mcp                       | 9.42                     | minecraft.jar                                     | None                                     |
	| U     | FML                       | 8.0.99.99                | forge-1.12.2-14.23.2.2611-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | forge                     | 14.23.2.2611             | forge-1.12.2-14.23.2.2611-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | spongeapi                 |                          | forge-1.12.2-14.23.2.2611-universal.jar           | None                                     |
	| U     | sponge                    |                          | forge-1.12.2-14.23.2.2611-universal.jar           | None                                     |
	| U     | advancedrocketrycore      | 1                        | minecraft.jar                                     | None                                     |
	| U     | opencomputers|core        | 1.7.2.67                 | minecraft.jar                                     | None                                     |
	| U     | elucore                   | 1.0                      | minecraft.jar                                     | None                                     |
	| U     | actuallyadditions         | 1.12.2-r133              | ActuallyAdditions-1.12.2-r133.jar                 | None                                     |
	| U     | actuallybaubles           | 1.1                      | ActuallyBaubles-1.12-1.1.jar                      | None                                     |
	| U     | advancedrocketry          | 1.4.0.-63                | AdvancedRocketry-1.12.2-1.4.0-63.jar              | None                                     |
	| U     | ae2stuff                  | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                     | None                                     |
	| U     | akashictome               | 1.2-10                   | AkashicTome-1.2-10.jar                            | None                                     |
	| U     | appleskin                 | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| U     | appliedenergistics2       | rv5-stable-10            | appliedenergistics2-rv5-stable-10.jar             | None                                     |
	| U     | architecturecraft         | @VERSION@                | architecturecraft-1.12-2.68.jar                   | None                                     |
	| U     | aroma1997core             | 1.3.0.2                  | Aroma1997Core-1.12.2-1.3.0.2.jar                  | None                                     |
	| U     | aroma1997sdimension       | 1.3.0.0.b37              | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar | None                                     |
	| U     | astralsorcery             | 1.8.5                    | astralsorcery-1.12.2-1.8.5.jar                    | None                                     |
	| U     | autoreglib                | 1.3-15                   | AutoRegLib-1.3-15.jar                             | None                                     |
	| U     | badwithernocookiereloaded | 1.12.2-2.12              | badwithernocookiereloaded-1.12.2-2.12.jar         | None                                     |
	| U     | base                      | 3.7.0                    | base-1.12.2-3.7.0.jar                             | None                                     |
	| U     | baubles                   | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
	| U     | bdlib                     | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                      | None                                     |
	| U     | bedpatch                  | 2.2                      | bedpatch-2.2-1.12.2.jar                           | None                                     |
	| U     | betteradvancements        | 0.0.5.17                 | BetterAdvancements-1.12.2-0.0.5.17.jar            | None                                     |
	| U     | betterbuilderswands       | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar   | None                                     |
	| U     | bibliocraft               | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar                 | None                                     |
	| U     | binniecore                | 2.5.0.131                | binnie-mods-1.12.2-2.5.0.131.jar                  | None                                     |
	| U     | botany                    | 2.5.0.131                | binnie-mods-1.12.2-2.5.0.131.jar                  | None                                     |
	| U     | binniedesign              | 2.5.0.131                | binnie-mods-1.12.2-2.5.0.131.jar                  | None                                     |
	| U     | extrabees                 | 2.5.0.131                | binnie-mods-1.12.2-2.5.0.131.jar                  | None                                     |
	| U     | extratrees                | 2.5.0.131                | binnie-mods-1.12.2-2.5.0.131.jar                  | None                                     |
	| U     | genetics                  | 2.5.0.131                | binnie-mods-1.12.2-2.5.0.131.jar                  | None                                     |
	| U     | blockcraftery             | 0.1.3                    | blockcraftery-0.1.3.jar                           | None                                     |
	| U     | bookshelf                 | 2.3.537                  | Bookshelf-1.12.2-2.3.537.jar                      | None                                     |
	| U     | botania                   | r1.10-353                | Botania r1.10-353.jar                             | None                                     |
	| U     | brandonscore              | 2.4.0                    | BrandonsCore-1.12-2.4.0.152-universal.jar         | None                                     |
	| U     | careerbees                | 1.0                      | careerbees-0.4.0.jar                              | None                                     |
	| U     | chameleon                 | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| U     | chesttransporter          | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                 | None                                     |
	| U     | chisel                    | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                      | None                                     |
	| U     | chiselsandbits            | 14.16                    | chiselsandbits-14.16.jar                          | None                                     |
	| U     | clumps                    | 2.0.0                    | Clumps-3.0.0.jar                                  | None                                     |
	| U     | codechickenlib            | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar     | None                                     |
	| U     | cofhcore                  | 4.3.10                   | CoFHCore-1.12.2-4.3.10.5-universal.jar            | None                                     |
	| U     | cofhworld                 | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar           | None                                     |
	| U     | comforts                  | 1.1.0.2                  | comforts-1.12.2-1.1.0.2.jar                       | None                                     |
	| U     | compacter                 | 1.3.0.3                  | compacter-1.3.0.3-mc1.12.2.jar                    | None                                     |
	| U     | compactmachines3          | 3.0.7                    | compactmachines3-1.12.2-3.0.7-b197.jar            | None                                     |
	| U     | compactsolars             | 1.12.2-5.0.17.340        | CompactSolars-1.12.2-5.0.17.340-universal.jar     | None                                     |
	| U     | cookingforblockheads      | 6.3.17                   | CookingForBlockheads_1.12.1-6.3.17.jar            | None                                     |
	| U     | crafttweaker              | 4.1.6                    | CraftTweaker2-1.12-4.1.6.jar                      | None                                     |
	| U     | crafttweakerjei           | 2.0.0                    | CraftTweaker2-1.12-4.1.6.jar                      | None                                     |
	| U     | danknull                  | 1.4.33                   | DankNull-1.12-1.4.33.jar                          | None                                     |
	| U     | darkutils                 | 1.8.207                  | DarkUtils-1.12.2-1.8.207.jar                      | None                                     |
	| U     | deepresonance             | 1.6.0                    | deepresonance-1.12-1.6.0.jar                      | None                                     |
	| U     | diethopper                | 1.1                      | diethopper-1.1.jar                                | None                                     |
	| U     | dirt2path                 | 1.7.0                    | dirt2path-1.7.0.jar                               | None                                     |
	| U     | draconicevolution         | 2.3.10                   | Draconic-Evolution-1.12-2.3.10.284-universal.jar  | None                                     |
	| U     | eleccore                  | 1.8.434                  | ElecCore-1.12.2-1.8.434.jar                       | None                                     |
	| U     | elevatorid                | 1.3.6                    | ElevatorMod-1.12.2-1.3.6.jar                      | None                                     |
	| U     | elulib                    | 0.1.12                   | elulib-0.1.12.jar                                 | None                                     |
	| U     | embers                    | 0.230                    | embers-0.230.jar                                  | None                                     |
	| U     | enderstorage              | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar       | None                                     |
	| U     | engineersworkshop         | 1.0.6.31                 | EngineersWorkshopReborn-1.12.2-1.0.6.31.jar       | None                                     |
	| U     | environmentaltech         | 1.12.2-2.0.8a            | environmentaltech-1.12.2-2.0.8a.jar               | None                                     |
	| U     | etlunar                   | 1.12.2-2.0.8a            | etlunar-1.12.2-2.0.8a.jar                         | None                                     |
	| U     | exchangers                | 1.12.2-2.7.1             | Exchangers-1.12.2-2.7.1.jar                       | None                                     |
	| U     | extracells                | 2.5.11                   | ExtraCells-1.12.2-2.5.11a48.jar                   | None                                     |
	| U     | extrautils2               | 1.0                      | extrautils2-1.12-1.7.5.jar                        | None                                     |
	| U     | bigreactors               | 1.12.2-0.4.5.46          | ExtremeReactors-1.12.2-0.4.5.46.jar               | None                                     |
	| U     | fencejumper               | 1.0.3                    | fencejumper-1.12-1.0.3.jar                        | None                                     |
	| U     | flatcoloredblocks         | mc1.12-6.6               | flatcoloredblocks-mc1.12-6.6.jar                  | None                                     |
	| U     | fluxnetworks              | 3.0.5                    | fluxnetworks-1.12.2-3.0.5.jar                     | None                                     |
	| U     | foamfix                   | 0.9.2-1.12.2             | foamfix-0.9.2-1.12.2-law.jar                      | None                                     |
	| U     | forestry                  | 5.8.0.256                | forestry_1.12.2-5.8.0.256.jar                     | None                                     |
	| U     | forgelin                  | 1.6.0                    | Forgelin-1.6.0.jar                                | None                                     |
	| U     | ftblib                    | 5.0.0.14                 | FTBLib-5.0.0.14.jar                               | None                                     |
	| U     | ftbutilities              | 5.0.0.11                 | FTBUtilities-5.0.0.11.jar                         | None                                     |
	| U     | gadgetrycore              | 0.2.0                    | gadgetrycore-0.2.0.jar                            | None                                     |
	| U     | gadgetrymachines          | 0.2.1                    | gadgetrymachines-0.2.1.jar                        | None                                     |
	| U     | gendustry                 | 1.6.5.8                  | gendustry-1.6.5.8-mc1.12.2.jar                    | None                                     |
	| U     | gravestone                | 1.10.1                   | gravestone-1.10.1.jar                             | None                                     |
	| U     | guideapi                  | 1.12-2.1.4-57            | Guide-API-1.12-2.1.4-57.jar                       | None                                     |
	| U     | immersiveengineering      | 0.12-79                  | ImmersiveEngineering-0.12-79.jar                  | None                                     |
	| U     | immersivepetroleum        | @VERSION@                | immersivepetroleum-1.12.2-1.1.7.jar               | None                                     |
	| U     | ic2                       | 2.8.16-ex112             | industrialcraft-2-2.8.16-ex112.jar                | None                                     |
	| U     | industrialforegoing       | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.8.5-127.jar          | None                                     |
	| U     | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | None                                     |
	| U     | ironbackpacks             | 1.12.2-3.0.5-6           | IronBackpacks-1.12.2-3.0.5-6.jar                  | None                                     |
	| U     | ironchest                 | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                   | None                                     |
	| U     | jei                       | 4.8.5.147                | jei_1.12.2-4.8.5.147.jar                          | None                                     |
	| U     | jeibees                   | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                      | None                                     |
	| U     | journeymap                | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                       | None                                     |
	| U     | kleeslabs                 | 5.3.2                    | KleeSlabs_1.12-5.3.2.jar                          | None                                     |
	| U     | libvulpes                 | 0.2.8.-27                | LibVulpes-1.12.2-0.2.8-27-universal.jar           | None                                     |
	| U     | longfallboots             | 1.2.1a                   | longfallboots-1.2.1a.jar                          | None                                     |
	| U     | lostcities                | 2.0.5                    | lostcities-1.12-2.0.5.jar                         | None                                     |
	| U     | magicbees                 | 1.0                      | MagicBees-1.12.2-3.1.9.jar                        | None                                     |
	| U     | malisiscore               | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                      | None                                     |
	| U     | malisisdoors              | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| U     | mantle                    | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                          | None                                     |
	| U     | mcjtylib_ng               | 2.6.6                    | mcjtylib-1.12-2.6.6.jar                           | None                                     |
	| U     | mcmultipart               | 2.4.1                    | MCMultiPart-2.4.1.jar                             | None                                     |
	| U     | minetogether              | unspecified              | minetogether-1.10.2-1.8.7.jar                     | None                                     |
	| U     | minetogetherserver        | unspecified              | minetogether-1.10.2-1.8.7.jar                     | None                                     |
	| U     | mob_grinding_utils        | 0.3.4                    | MobGrindingUtils-0.3.4.jar                        | None                                     |
	| U     | modtweaker                | 4.0.8                    | modtweaker-4.0.8.jar                              | None                                     |
	| U     | morphtool                 | 1.2-16                   | Morph-o-Tool-1.2-16.jar                           | None                                     |
	| U     | morpheus                  | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                           | None                                     |
	| U     | mtlib                     | 3.0.4                    | MTLib-3.0.4.jar                                   | None                                     |
	| U     | natura                    | 1.12.2-4.3.2.42          | natura-1.12.2-4.3.2.42.jar                        | None                                     |
	| U     | naturescompass            | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                   | None                                     |
	| U     | netherportalfix           | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar                 | None                                     |
	| U     | nice                      | 0.2.0                    | nice-1.12-0.2.0.jar                               | None                                     |
	| U     | neid                      | 1.5.4.2                  | NotEnoughIDs-1.5.4.2.jar                          | None                                     |
	| U     | notenoughwands            | 1.6.1                    | notenoughwands-1.12-1.6.1.jar                     | None                                     |
	| U     | nuclearcraft              | 2.9e                     | NuclearCraft-2.9e--1.12.2.jar                     | None                                     |
	| U     | opencomputers             | 1.7.2.67                 | OpenComputers-MC1.12.2-1.7.2.67.jar               | None                                     |
	| U     | p455w0rdslib              | 2.0.29                   | p455w0rdslib-1.12-2.0.29.jar                      | None                                     |
	| U     | harvestcraft              | 1.12.2r                  | Pam's HarvestCraft 1.12.2r.jar                    | None                                     |
	| U     | placebo                   | 1.3.1                    | Placebo-1.12.2-1.3.1.jar                          | None                                     |
	| U     | platforms                 | 1.4.5                    | platforms-1.12.0-1.4.5.jar                        | None                                     |
	| U     | quark                     | r1.4-122                 | Quark-r1.4-122.jar                                | None                                     |
	| U     | quickleafdecay            | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                 | None                                     |
	| U     | rangedpumps               | 0.5                      | rangedpumps-0.5.jar                               | None                                     |
	| U     | reborncore                | 3.6.11.220               | RebornCore-1.12.2-3.6.11.220-universal.jar        | None                                     |
	| U     | redstonearsenal           | 2.3.10                   | RedstoneArsenal-1.12.2-2.3.10.4-universal.jar     | None                                     |
	| U     | redstoneflux              | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar           | None                                     |
	| U     | xreliquary                | 1.12.2-1.3.4.757         | Reliquary-1.12.2-1.3.4.757.jar                    | None                                     |
	| U     | rftools                   | 7.31                     | rftools-1.12-7.31.jar                             | None                                     |
	| U     | rftoolscontrol            | 1.8.1                    | rftoolsctrl-1.12-1.8.1.jar                        | None                                     |
	| U     | roots                     | 0.104                    | roots-2-0.104.jar                                 | None                                     |
	| U     | rustic                    | 1.0.2                    | rustic-1.0.2.jar                                  | None                                     |
	| U     | secretroomsmod            | 5.5.2                    | secretroomsmod-1.12.2-5.5.2.jar                   | None                                     |
	| U     | shetiphiancore            | 3.5.6                    | shetiphiancore-1.12.0-3.5.6.jar                   | None                                     |
	| U     | signals                   | 1.0                      | Signals-1.12.2-1.2.2-5-universal.jar              | None                                     |
	| U     | simplevoidworld           | 1.2.0.9                  | Simple-Void-World-1.12-1.2.0.9-universal.jar      | None                                     |
	| U     | snad                      | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                        | None                                     |
	| U     | sonarcore                 | 5.0.6                    | sonarcore-1.12.2-5.0.6.jar                        | None                                     |
	| U     | soulshardstow             | 1.12-2.7.6-56            | SoulShards-TOW-1.12-2.7.6-56.jar                  | None                                     |
	| U     | stevescarts               | 2.4.18.92                | StevesCarts-1.12.2-2.4.18.92.jar                  | None                                     |
	| U     | storagedrawers            | 1.12-5.2.5               | StorageDrawers-1.12.2-5.3.5.jar                   | None                                     |
	| U     | storagedrawersextra       | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar               | None                                     |
	| U     | tconstruct                | 1.12.2-2.9.1.65          | TConstruct-1.12.2-2.9.1.65.jar                    | None                                     |
	| U     | teslacorelib              | 1.0.13                   | tesla-core-lib-1.12-1.0.13.jar                    | None                                     |
	| U     | teslacorelib_registries   | 1.0.13                   | tesla-core-lib-1.12-1.0.13.jar                    | None                                     |
	| U     | theoneprobe               | 1.4.21                   | theoneprobe-1.12-1.4.21.jar                       | None                                     |
	| U     | thermalcultivation        | 0.1.5                    | ThermalCultivation-1.12.2-0.1.5.3-universal.jar   | None                                     |
	| U     | thermaldynamics           | 2.3.10                   | ThermalDynamics-1.12.2-2.3.10.4-universal.jar     | None                                     |
	| U     | thermalexpansion          | 5.3.10                   | ThermalExpansion-1.12.2-5.3.10.15-universal.jar   | None                                     |
	| U     | thermalfoundation         | 2.3.10                   | ThermalFoundation-1.12.2-2.3.10.6-universal.jar   | None                                     |
	| U     | thutcore_compat           | 1.0                      | thutcore-1.12.2-5.16.2.jar                        | None                                     |
	| U     | thutcore                  | 5.16.2                   | thutcore-1.12.2-5.16.2.jar                        | None                                     |
	| U     | thuttech                  | 6.0.15                   | thuttech-1.12.2-6.0.15.jar                        | None                                     |
	| U     | tinkertoolleveling        | 1.12-1.0.3.DEV.56fac4f   | TinkerToolLeveling-1.12-1.0.3.jar                 | None                                     |
	| U     | topaddons                 | 1.12.2-1.5.0             | topaddons-1.12.2-1.5.0.jar                        | None                                     |
	| U     | torchmaster               | 1.6.1.53                 | torchmaster_1.12.2-1.6.1.53.jar                   | None                                     |
	| U     | traverse                  | 1.3.1                    | Traverse-1.12.1-1.3.1.jar                         | None                                     |
	| U     | unidict                   | 1.12.2-2.4c              | UniDict-1.12.2-2.4c.jar                           | None                                     |
	| U     | valkyrielib               | 1.12.2-2.0.8a            | valkyrielib-1.12.2-2.0.8a.jar                     | None                                     |
	| U     | wanionlib                 | 1.12.2-1.5               | WanionLib-1.12.2-1.5.jar                          | None                                     |
	| U     | waystones                 | 4.0.20                   | Waystones_1.12.2-4.0.20.jar                       | None                                     |
	| U     | whoosh                    | 0.1.8                    | Whoosh-1.12.2-0.1.8-universal.jar                 | None                                     |
	| U     | wct                       | 3.9.62                   | WirelessCraftingTerminal-1.12.2-3.9.62.jar        | None                                     |
	| U     | xnet                      | 1.6.8                    | xnet-1.12-1.6.8.jar                               | None                                     |
	| U     | xtones                    | 1.12-1.0.8-11            | Xtones-1.12-1.0.8-11.jar                          | None                                     |
	| U     | yabba                     | 1.1.0.9                  | YABBA-1.1.0.9.jar                                 | None                                     |
	| U     | zerocore                  | 1.12-0.1.1.0             | zerocore-1.12-0.1.1.0.jar                         | None                                     |
	| U     | bungeetablistplus         | 2.8.3                    | BungeeTabListPlus_SpongeBridge-2.8.3.jar          | None                                     |
	| U     | changeskin                | 3.1-eaefd2d              | ChangeSkinSponge.jar                              | None                                     |
	| U     | flexiblelogin             | 0.17.1                   | flexiblelogin-0.17.1.jar                          | None                                     |
	| U     | griefprevention           | 1.12.2-4.3.0.562         | griefprevention-1.12.2-4.3.0.562.jar              | None                                     |
	| U     | karoglansigneditor        | 3.0                      | KaroglanSignEditor-3.0.jar                        | None                                     |
	| U     | luckperms                 | 4.1.43                   | LuckPerms-Sponge-4.1.43.jar                       | None                                     |
	| U     | market                    | 1.0-SNAPSHOT             | Market-0.1.1.jar                                  | None                                     |
	| U     | mmcrestrict               | 1.4.1                    | MMCRestrict-1.4.1-API-7.jar                       | None                                     |
	| U     | nucleus                   | 1.3.4-S7.0               | Nucleus-1.3.4-S7.0-MC1.12.2-plugin.jar            | None                                     |
	| U     | placeholderapi            | 4.4                      | PlaceholderAPI-4.4.jar                            | None                                     |
	| U     | pjc                       | 0.2.1                    | projectcore-7.0.0-0.2.1.jar                       | None                                     |
	| U     | pjw                       | 0.12.2                   | projectworlds-7.1.0-0.12.2.jar                    | None                                     |
	| U     | totaleconomy              | 1.8.0                    | TotalEconomy-1.8.0.jar                            | None                                     |
	| U     | ultimatechat              | 1.8.5                    | UltimateChat-1.8.5-b151-Universal.jar             | None                                     |
	| U     | worldedit                 | 6.1.9-SNAPSHOT           | worldedit-sponge-6.1.9-SNAPSHOT-dist.jar          | None                                     |

	Loaded coremods (and transformers): 
SpongeCoremod (forge-1.12.2-14.23.2.2611-universal.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-63.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
BedPatch (bedpatch-2.2-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  
Plugin (NotEnoughIDs-1.5.4.2.jar)
  ru.fewizz.neid.asm.Transformer
CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.2.jar)
  c4.comforts.asm.SleepTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-77-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (Quark-r1.4-122.jar)
  vazkii.quark.base.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-79-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.5.2.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
`

**Comment by games647** [comment]
Thank you, it looks like that they use a Minecraft version prefix. This could be something that Sponge cannot handle. I'll backport a patch for it.
