### ISSUE TITLE
player lost connection : time out

### ISSUE THREAD

**Issue by subtank** [games647/FlexibleLogin#126]
when use the flexiblelogin it always login hardly.how to setting the plugin to not time out?

**Comment by subtank** [comment]
with plugin:
spongeforge @ 3002
Nucleus @ 1.3.6
GP @ 4.3.0.537
LP @ 4.1.61
SkyClaims @ 0.27.2

**Comment by games647** [comment]
You can configure the timeout delay in the configuration file.

**Comment by subtank** [comment]
console still report this
`[net.minecraft.network.NetHandlerPlayServer]: subtank lost connection: Timed out`

**Comment by games647** [comment]
This not an error just an information.

**Comment by subtank** [comment]
but when i disable the flexiblelogin it didn't come out

**Comment by subtank** [comment]
[latest.zip](https://github.com/games647/FlexibleLogin/files/1887490/latest.zip)

**Comment by games647** [comment]
You are using a incompatible combination of Sponge API with Forge.

Please follow this: 
https://docs.spongepowered.org/stable/en/server/getting-started/implementations/spongeforge.html

**Comment by subtank** [comment]
i know i run a high version Forge.but agricraft need above 2618 to run...
so here are two choice for this problem:1) downgrade the forge to 2611 and delete the agricraft mod. 2) nothing change and keep this problem.right?
