### ISSUE TITLE
Other entities cannot move during register/login

### ISSUE THREAD

**Issue by LeChevalierDOr** [games647/FlexibleLogin#127]
EN :

When a person connects to the server, while the player enters his / login or his / register **ALL**  mob passive and hostile mob entities are blocked: they do not move anymore! Just the sound! sometimes the players rollback! Once the player who was logging in made his / login or / register everything becomes normal again. I can not open the server without it please help me ! 

Info: sponge API 7.1.0 
Other plugins: yes 
Server version 1.12.2 
Mod: yes

FR :

Quand une personne se connecte sur le serveur, pendant que le joueur entre son /login ou son /register **TOUS**  les entités mob passive et mob hostile sont bloqués : ils ne bouge plus ! Juste le son ! Des fois les joueurs ont des rollback ! Une fois le joueur qui était en train de se connecter a fais son /login ou /register tout redevient normal. Je ne peux pas ouvrir le serveur sans ça s'il-vous-plaît aidez-moi !

Info : sponge API 7.1.0 
Autre plugins : oui  
Version serveur 1.12.2 
Mod : oui

**Comment by games647** [comment]
Plugin version?

**Comment by LeChevalierDOr** [comment]
Latest version (0.17.2 ?) and I tried 1.7

**Comment by games647** [comment]
Do you tried another sponge forge version too?

**Comment by LeChevalierDOr** [comment]
I can not change version because it is an automatic installation of omgserv

**Comment by LeChevalierDOr** [comment]
it's not **after**  but **during** login / register

**Comment by LeChevalierDOr** [comment]
the plugin seems to work without any other plugin

**Comment by games647** [comment]
Could you try to reproduce it on a local server using the exact same server version? Please that version here too. This sounds more like a event filter bug.

**Comment by games647** [comment]
>the plugin seems to work without any other plugin

So it works without other plugins?

**Comment by LeChevalierDOr** [comment]
Yes

**Comment by LeChevalierDOr** [comment]
do you want me to try on a local server?

**Comment by games647** [comment]
>do you want me to try on a local server?

Yes and you still didn't posted the sponge implementation version (like SpongeForge or SpongeVanilla).

**Comment by LeChevalierDOr** [comment]
Excuse me I did not see. the version I use is: 1.12.2 (7.1.0-BETA-2819 / Forge 14.23.1.2555)

**Comment by LeChevalierDOr** [comment]
I'll keep you informed

**Comment by games647** [comment]
Could you post your server log too please. Maybe there is an error.

**Comment by LeChevalierDOr** [comment]
No, there are no visible errors in the latest log and fml logs. Still want to see?

**Comment by games647** [comment]
Yes

**Comment by LeChevalierDOr** [comment]
ok please wait. I put the plugin on the server you want what logs: fml? latest?

**Comment by LeChevalierDOr** [comment]
@games647 

FR -

Le problème semble résolu merci beaucoup en faite il y'avais un plugin qui fessait des erreurs en console  (Negativy anti-cheat). J'aurais du regarder les logs plus sérieusement... désolé du dérangement...

Merci beaucoup ! 

EN -

the problem seem resolved thank you very much in made it y'avais a plugin that fessait errors in console (negativy anti-cheat). uncovered the watch logs more seriously ... sorry of disturbance ... 

Thank you very much!

**Comment by games647** [comment]
I'm happy that this bug is resolved. BTW: You could close the ticket too (-> mark it as resolved.)

**Comment by LeChevalierDOr** [comment]
@games647 

FR -

Le problème semble résolu merci beaucoup en faite il y'avais un plugin qui fessait des erreurs en console  (Negativy anti-cheat). J'aurais du regarder les logs plus sérieusement... désolé du dérangement...

Merci beaucoup ! 

EN -

the problem seem resolved thank you very much in made there had a plugin that was errors in console (negativy anti-cheat). uncovered the watch logs more seriously ... sorry of disturbance ... 

Thank you very much!
