### ISSUE TITLE
A few feature requests

### ISSUE THREAD

**Issue by GershonR** [games647/FlexibleLogin#13]
- Ability for an admin to change a users password
- Setting recovering information to prove account identity
- Maximum registrations per ip-address
- Locking a account for X amount of time after X amount of attempts
- Ability to /logout to prevent ip-sessions from auto-logging in
- Minimum password length

- [x] Ability for an admin to change a users password
- [x] Maximum registrations per ip-address
- [x] Locking a account for X amount of time after X amount of attempts
- [X] Ability to /logout to prevent ip-sessions from auto-logging in
- [X] Minimum password length

**Comment by games647** [comment]
Converted to task list:

- [ ] Ability for an admin to change a users password
- [ ] Setting recovering information to prove account identity
- [ ] Maximum registrations per ip-address
- [ ] Locking a account for X amount of time after X amount of attempts
- [X] Ability to /logout to prevent ip-sessions from auto-logging in
- [ ] Minimum password length

This will be edited if there changes.

**Comment by games647** [comment]
@GershonR What do you mean by "Setting recovering information to prove account identity"?

**Comment by GershonR** [comment]
Something along the lines of recovery questions or whatever the user wants to identify they created that account

**Comment by games647** [comment]
Ouh, okay. FlexibleLogin already has support for a recovery email address. So you need this too?

**Comment by GershonR** [comment]
How would the server send an email to the user? SMTP? and how would a user specify they want an email sent rather than having an admin manually check the recovery information they set

**Comment by games647** [comment]
Yes with SMTP. You can set the email with setemail if you are logged in.

**Comment by GershonR** [comment]
How would a user request for an email to be sent, and will the email allow them to change the password?

**Comment by games647** [comment]
If the user have set the email, they can type /forgotpassword and will receive an email with a new password.

**Comment by GershonR** [comment]
Ah I see that's very cool, you can delete the recovery thing then, that idea is awesome

**Comment by GershonR** [comment]
Any news on the other features?

**Comment by games647** [comment]
Sorry I was too busy recently.

**Comment by games647** [comment]
I'm going to continue working on this once 1.9 sponge is released.

**Comment by GershonR** [comment]
Isn't 1.9.4 Sponge beta already out?

**Comment by games647** [comment]
You are right. I checked it last week and there wasn't any build for it.
