### ISSUE TITLE
/login not working

### ISSUE THREAD

**Issue by evernife** [games647/FlexibleLogin#131]
![image](https://user-images.githubusercontent.com/11357801/39962924-21e62e96-5634-11e8-8344-f754c6aaad7f.png)

Using dev 49

MyConfig  https://pastebin.com/Pjg1SW7x

> Minecraft 1.12.2
> spongeforge-1.12.2-2655-7.1.0-BETA-3065.jar
> Forge 2655

**Comment by games647** [comment]
As always, please post your server log. This looks like FlexibleLogin went in failure mode.

**Comment by evernife** [comment]
Sorry for delay

Here it is, i tedted with dev 50

latest.log   -   https://pastebin.com/bCuRNErZ
debug.log   -   this one was too large, so, this is the end of the file https://pastebin.com/5KXP99bJ

**Comment by games647** [comment]
Could you please translate what error message says?

**Comment by evernife** [comment]
> Unknown command. Type /help to see the list of commands.

**Comment by games647** [comment]
I tried it multiple times and cannot reproduce this. Do you have database name set to flexiblelogin in your setup, because that's the only errors I got and after fixing it it works fine.

**Comment by evernife** [comment]
i will make a few more tests

**Comment by evernife** [comment]
Seems to be working fine on last version of Sponge.
(Some others plugins, like husky crates, have had issues caused by some sponge changes.)

![image](https://user-images.githubusercontent.com/11357801/41457576-800576a4-705a-11e8-980e-15fcb5117164.png)


Anyway, I haven't tested it on my working server, but, if i have any new problem related to this i will reopen it;
