### ISSUE TITLE
Easy Dupe

### ISSUE THREAD

**Issue by Lorrainrm** [games647/FlexibleLogin#138]
So
You can join the same account with multiples minecraft instances.
Just drop an item using one of the instances, the other instance will still have the item.
Free items for the whole server yaaaaaay!

**Comment by Lorrainrm** [comment]
Probably non related to your plugin, but just a heads up :(

**Comment by evernife** [comment]
Lol, nonsense...

When you try to join an account that is already on the server the minecraft don't allow it...

Can you show us a few screenshots: D

**Comment by Lorrainrm** [comment]
It's been an issue, we believe is on Sponge. When you got a bit of delay (ping in this case), like, Host in Canada and Players from Brazil, which is my scenario, its possible and easy to do this. :(

Like 100% of the time, you can join same account in multiple instances and this is an issue even for online-mode true.

Managed to get a developer to make us a plugin to deny this. But vanilla is stupid for now.

**Comment by evernife** [comment]
Meu servidor é no Canada e eu sou do Brasil '-'

Nunca tive esse problema.
Como eu comentei, é bem improvável que um senário desse aconteça (nunca vi ninguém relatar algo nem que seja parecido).
Se tiver prints, só mandar que a gente analisa.

Eu sou desenvolvedor no caso, mas para ser sincero, não vejo isso acontecendo de forma alguma.
(Para evitar não seria complicado, supondo que isso seja possível, basta toda vez que alguém entrar, ver se não existe já alguém logado com o mesmo nome, tendo em vista que hoje em dias as checagens são por UUID, verificar o nome deveria resolver)

Alem disso, sugiro fechar a issue, afinal, não tem muito haver com o FlexibleLogin...

**Comment by Lorrainrm** [comment]
Fecho sim. Bom, posso mandar o Plugin que resolveu o problema pra você dar uma olhada.
E tente assim:
Abra 2 instancias pelo technic, por exemplo. Deixe ambos preparados para login. Entre com os 2 ao mesmo tempo, os 2 vão conseguir acessar normalmente, como se fosse 1 uma instancia recebendo/enviando packets e a outra, nada. Assim, era possível dupar infinitamente. Mole mole.

Mandei isso num chat de donos de pixelmon, e parece não ser só comigo. Tanto que esse plugin foi meio que uma colaboração entre donos preocupados com isso. Como disse, é irrelevante tá só pra original ou pra piratas também, que o problema é o mesmo :(

**Comment by evernife** [comment]
Me passa seu discord para mim entrar em contato

**Comment by Lorrainrm** [comment]
Eisenbahn
#5615
