### ISSUE TITLE
Nag Messages & Max Walk Distance

### ISSUE THREAD

**Issue by GershonR** [games647/FlexibleLogin#14]
If you login on the server you will only get 1 message telling you to /login or /register. I think it should be replaced with if the user hasn't registered it will tell them they have to /register because saying /login might confuse them.

An unregistered user can also walk around and when they try to interact they don't get any messages reminded them to /register or they won't be able to do anything, because most think it's an issue with the server. And to go with that, add a maximum distance they can walk before being teleported back to their log out location usually something like 2-10 blocks.

**Comment by games647** [comment]
I think that's a Sponge issue.

**Comment by GershonR** [comment]
Cant you make it send a message every 5-10 seconds if a user dident use /register successfully?
