### ISSUE TITLE
ipAutoLogin teleports to location of section "teleportConfig"

### ISSUE THREAD

**Issue by x3rAx** [games647/FlexibleLogin#141]
Hi,

when enabling the "teleportConfig" option together with "ipAutoLogin" I am teleported the the configured location while also being logged in. 

When I then enter `/login <my-password>` the server tells me that I'm already logged in but I am teleported back to where I left the server.

**Comment by games647** [comment]
Yes and that's sounds like the expected behavior. Unlogged in players will be teleported to the configured location and once they login they are teleported back.
