### ISSUE TITLE
Logout and then Login will be teleported into room

### ISSUE THREAD

**Issue by willis1030** [games647/FlexibleLogin#15]
Hello, when I stand on front of a iron_door, and I logout and then login, I am teleported into the room! The situation is that Iron_door and me are on the same block, door is on the north size of the block, then I am teleported to the north size block of the door. But not using FlexibleLogin will be normal. my version is spongevanilla-1.8.9-4.2.0-BETA-343, spongevanilla-1.8.9-3.1.0-BETA-248, both of them the same bug!

**Comment by games647** [comment]
Do you have teleportConfig activated?

**Comment by willis1030** [comment]
teleportConfig {
    coordX=0
    coordY=0
    coordZ=0
    # Should the plugin use the default spawn from the world you specify below
    defaultSpawn=false
    enabled=false
    # Spawn world or let it empty to use the default world specified in the server properties
    worldName=""
}

**Comment by games647** [comment]
I'm guessing it's a sponge issue, because FastLogin tries to set safe-location using the Sponge API.
