### ISSUE TITLE
Error while creating file

### ISSUE THREAD

**Issue by Koteyk0o** [games647/FlexibleLogin#156]
Hi, i use FlexibleLogin 0.17.4 with spongeforge-1.12.2-2768-7.1.6-RC3666, and i want to use local storage. With default config i have crash with error "Error while creating file "/plugins""
Any ideas?

Log: https://pastebin.com/v52h5hA6

**Comment by games647** [comment]
Do you checked if the path already exists? Could please post the exact config value you chose, because `/plugins` doesn't refer to the subfolder `plugins` instead the leading `/` will go to the root directory.

**Comment by Koteyk0o** [comment]
Hello, thanks for answer. Config is default.

Other plugins (for example, LuckPerms) create their files normally. The config is created normally, the localization file is created normally, but the database cannot be created.

Config: https://pastebin.com/ywJGw6NQ

**Comment by games647** [comment]
Could you please test a development build? I think it's weird that FlexibleLogin wants to write in the plugins folder, although Sponge has a separate configs folder.

**Comment by Koteyk0o** [comment]
Yeah, of course, where i can download it?

**Comment by Koteyk0o** [comment]
Flexiblelogin 0.18 it's dev build? I tried, the same error, but the path in the error is different.

Log: https://pastebin.com/K1B0b1FQ

Updated Sponge to spongeforge-1.12.2-2768-7.1.6-RC3671
And forge to forge-1.12.2-14.23.5.2836-universal
I also tried on the server without plugins and mods (except Sponge)

**Comment by games647** [comment]
Do you have some kind of special characters in the absolute path to the server. Could you maybe also try a stable version of spongeforge? I just tried to reproduce it, but it worked for me using:

* spongeforge-1.12.2-2768-7.1.5
* forge-1.12.2-14.23.5.2768-universal

**Comment by Koteyk0o** [comment]
No, there are no special characters in the path to the server folder (Tested on Windows 10 and Ubuntu with Java 8)
Path to the plugins folder - `C:\Users\aleee\Desktop\Server\plugins`

I downloaded spongeforge-1.12.2-2768-7.1.5 and forge-1.12.2-14.23.5.2768-universal, and i have same error.

Full server start log: https://pastebin.com/trcYfTNs

**Comment by games647** [comment]
I published a change that will output the generated jdbc could you run the newest build and post the again.

**Comment by Koteyk0o** [comment]
Yes, i ran, log: https://pastebin.com/mCaw7FW4

**Comment by games647** [comment]
Okay that took a while. I think I found it. Could you try it out?

**Comment by Koteyk0o** [comment]
Yeah, tested. Log: https://pastebin.com/Dph6JSqD

**Comment by Koteyk0o** [comment]
Yeah, thanks, build #61 worked
