### ISSUE TITLE
Some Errors

### ISSUE THREAD

**Issue by GershonR** [games647/FlexibleLogin#16]
http://pastebin.com/iRSSkjbN

**Comment by games647** [comment]
Does this run on multiple servers or do you register players while they are online?

**Comment by GershonR** [comment]
Only one of my server run it and they can only register by themself when they are online, it looks like rare error I never saw that before

**Comment by games647** [comment]
Do you had the issue again?

**Comment by GershonR** [comment]
No, it looked pretty random I just happened to come across it when checking logs, it could of happend before but i'm not sure.
