### ISSUE TITLE
BCrypt secret

### ISSUE THREAD

**Issue by Angrigo** [games647/FlexibleLogin#162]
Hello, could we have the possibility to set a bcrypt hash? I'm planning to build another login system using the same database so I need the hash to check password.
Also, could you update $2y$ bcrypt prefix to $2a$ ? It seems newer

**Comment by games647** [comment]
>Also, could you update $2y$ bcrypt prefix to $2a$ ? It seems newer

There is actually no difference ([ref](https://stackoverflow.com/questions/15733196/where-2x-prefix-are-used-in-bcrypt)). It was changed to 2y to provide compatibility with PHP. 

>Hello, could we have the possibility to set a bcrypt hash? 

The user object has already a method to set the hash. Only afterwards the change have to be flushed to the database.
