### ISSUE TITLE
Dup bug

### ISSUE THREAD

**Issue by Heriptik** [games647/FlexibleLogin#167]
Dup bug

**Comment by games647** [comment]
Please use the security tap at the top of the page. It's built for that kind of stuff.

**Comment by Heriptik** [comment]
I sent you in private message on the sponge forum because the security page is not active (for me on github)

**Comment by Heriptik** [comment]
News ? If the dup spreads, all servers that use Flexiblelogin could be impacted

**Comment by TuxCoding** [comment]
Fixed in #172
