### ISSUE TITLE
Access to inventory before logging in.

### ISSUE THREAD

**Issue by denisjo7** [games647/FlexibleLogin#179]
I am experiencing the same problem that was reported in Issue #74 
It is almost exactly the same problem. Access to the inventory is permitted, but no items can be dropped or moved. But access to the pokémon sub menu and its characteristics is allowed, as well as alteration of these characteristics, such as the movements of the pokémon.

MC Version: `1.12.2`
Forge: `forge-1.12.2-14.23.5.2854`
Sponge: `spongeforge-1.12.2-2838-7.2.3`
FlexibleLogin: `flexiblelogin-0.17.4` and `flexiblelogin-0.19-SNAPSHOT` too.
Pixelmon: `Pixelmon-1.12.2-8.0.2`

**Comment by TuxCoding** [comment]
So while the players are not logged in?

**Comment by denisjo7** [comment]
Exactly.

**Comment by Suim67** [comment]
I've the same problem !
