### ISSUE TITLE
v.0.9.1 breaks database from v.0.8 and earlier

### ISSUE THREAD

**Issue by GershonR** [games647/FlexibleLogin#18]
When I use the latest version it deletes the current database and requires everyone to re-register again.

**Comment by games647** [comment]
Do you had any errors on the first start of 0.9?

**Comment by GershonR** [comment]
No errors as far as I know, I can upload the database for you to test.

SpongeForge 1547

**Comment by games647** [comment]
Yeah good idea. If there was an error, the old database should be still there. So I could import it for you.

**Comment by GershonR** [comment]
http://uppit.com/2pdlo5mi8pma
http://uppit.com/ix3fvyi7p33f

**Comment by SourcePowered** [comment]
What SQL type ? H2? Or SQLite? Or...
The new version default sql type is H2, not SQLite...

**Comment by games647** [comment]
@SourcePowered They are different SQL storage system. 

https://en.wikipedia.org/wiki/SQLite
https://en.wikipedia.org/wiki/H2_(DBMS)

**Comment by games647** [comment]
@GershonR Do you have multiple database files in your flexiblelogin folder too?

BTW I only need the .mv file.

**Comment by SourcePowered** [comment]
@games647 YES, I know that, but I mean is, what Database version he used in old version of plugin, if he use SQLite in config, and update to new version, but new version's config is "H2", I think it will not work any more. So, I think he should to check his config file.

**Comment by GershonR** [comment]
Here is the current config for the working one:
http://pastebin.com/8F4mAgaQ

and I think I have much more accounts than 100 records and I only have the trace and normal database in my folder that's it

**Comment by games647** [comment]
@SourcePowered Sorry, in the past I had some users who doesn't understand how to the ticket system.

If it was SQLite before I could export the old data as SQL inserts and import it in a new one. 

@GershonR I browsed the database you sent me and there is only the new table, the old one doesn't exist anymore.

**Comment by SourcePowered** [comment]
OK, you've had a long day. I've never seen a developer so responsible.

**Comment by GershonR** [comment]
Here is another one, it's the latest one which the server uses, it should definitely have probably over 1,000 accounts.

http://uppit.com/30i6aydrb49h

**Comment by games647** [comment]
Ok there are already 1.800 accounts with the new database schema. and I couldn't find any duplicates.

**Comment by GershonR** [comment]
That's the original one, when it gets converted all of that gets deleted and a new file is made.

**Comment by GershonR** [comment]
Any news on this?

**Comment by games647** [comment]
No sorry, the old database is gone.

**Comment by GershonR** [comment]
Do you want me to reupload it then for you to test?

**Comment by games647** [comment]
No sorry, I couldn't find the old database table.

**Comment by GershonR** [comment]
Can you make a importer so it will load the old database and add the data to the new one?

**Comment by GershonR** [comment]
I have the old database I backed it up before updating and when the plugin was deleting the database I downgraded back

**Comment by games647** [comment]
I could try it.

**Comment by GershonR** [comment]
I just decided to let it regenerate everything
