### ISSUE TITLE
Version for API 4.x

### ISSUE THREAD

**Issue by GershonR** [games647/FlexibleLogin#23]
Since it looks like API 5 won't be stable for some time, and players can run command, chat, move around which is a huge issue

**Comment by games647** [comment]
I tried it with 5.X. It works for very well. Maybe it something with your specific version.

**Comment by GershonR** [comment]
I mean it works well for API 5 but I'm still on 1.8.9 due to it being bleeding and still has issues

**Comment by GershonR** [comment]
Thank you kind sir
