### ISSUE TITLE
The suggestion for login teleporation

### ISSUE THREAD

**Issue by 5igm** [games647/FlexibleLogin#26]
In offline mode, a player can use any name to join game. Although FlexibleLogin can stop people who are not the owner of the account to do bad thing, people still can use F3 to check the position of the account used. For some people, they may utilize this fuction to set a trap to kill others. 
Could you add a function to protect innocent players from these spiteful actions?
I think if there is a function which teleporates all of the unlogin players to world spawn point forcely, and teleporate players back after they login into the game successfully, it will protect players better.

**Comment by games647** [comment]
It's already included in FlexibleLogin. It's in the config the teleport thing.
