### ISSUE TITLE
Add a strong language system

### ISSUE THREAD

**Issue by SourcePowered** [games647/FlexibleLogin#31]
I have mentioned this issue, but I think this is very important, so put forward again, please forgive me.
Attract more users, rather than let them update their own language.

1. Create a folder named "Messages" or "messages" (Oh ... case size is not a problem...... :P)...
2. Create some lang files in "M(m)essages" folder like:

```
message_en
message_zhcn
message_ru
message_(country code)
```

We don't need a file suffix (like *.lang), because the meaning of "message" is very clear ( But, this is not a problem, too... What do you want to do, just like that).
3. In config file, users can change what language file they need to use(For example: Language "message_en").
4. Then accept the pulls from other users, it is perfect.
5. Done!!!

**Comment by games647** [comment]
Or make use of the wiki?

**Comment by SourcePowered** [comment]
@games647 Sir, if you don't want to add it in to the plugin, of course, you can create a Wiki page,to display multi language configuration files, I think this is feasible.

**Comment by games647** [comment]
I added a little Github wiki guide.
