### ISSUE TITLE
Could you add a command for administrators to check users' e-mail address?

### ISSUE THREAD

**Issue by 5igm** [games647/FlexibleLogin#33]
Could you add a command for administrators to check users' e-mail address? If the server doesn't set mysql, it is impossible for administrators to check users' passport, e-mail address, etc. It is not convienient very much.

**Comment by games647** [comment]
Viewing the password is too dangerous. The admin shouldn't know the password of the users. That's why you hash it. 

>If the server doesn't set mysql, it is impossible for administrators to check users' passport, e-mail address, etc. It is not convienient very much.

You could use H2 database browser. I love to use SQLiteman for SQLite database and SquirellSQL for for everything else except MySQL.
