### ISSUE TITLE
Error: people can drop items before they login into the account.

### ISSUE THREAD

**Issue by 5igm** [games647/FlexibleLogin#34]
People can drop items before they login into the account. 
spongeforge-1.10.2-2073-5.0.0-BETA-1684

**Comment by 5igm** [comment]
FlexibleLogin v0.9.1
In addition, people also can use "e" to open inventory before they login into the account.

**Comment by games647** [comment]
>In addition, people also can use "e" to open inventory before they login into the account.

There is no way to prevent that.

**Comment by 5igm** [comment]
@games647 What is your meaning? There is no way to prevent drop things before they login?

**Comment by games647** [comment]
No my reply was for the thing I quoted.

**Comment by 5igm** [comment]
@games647 Excuse me. Thanks for your help.

**Comment by 5igm** [comment]
@games647  The problem is still existing. Now, if people use "q" to try to drop some items before login, items will not be dropped on the ground, but items will be deleted.
