### ISSUE TITLE
People can drop items before they login into the account - Continue

### ISSUE THREAD

**Issue by 5igm** [games647/FlexibleLogin#35]
https://github.com/games647/FlexibleLogin/issues/34#issuecomment-243394760
The problem is still existing. Now, if people use "q" to try to drop some items before login, items will not be dropped on the ground, but items will be deleted.

**Comment by games647** [comment]
That's a Sponge/Forge issue

**Comment by games647** [comment]
I created a ticket on Sponge's side.

**Comment by 5igm** [comment]
@games647 Thank you very much.

**Comment by 5igm** [comment]
Dose it be fixed?

**Comment by 5igm** [comment]
@games647

**Comment by games647** [comment]
You don't need to ping me. I'm already subscribed to this topic by answering to it.

I thought I got a response for this: https://github.com/SpongePowered/SpongeCommon/issues/528

**Comment by 5igm** [comment]
Does it mean the bug has been fixed?
In addition, players can use items before they login into server.

**Comment by games647** [comment]
>In addition, players can use items before they login into server.

I tried it. It's prevented for me.

**Comment by 5igm** [comment]
I installed BloodMagic-1.9.4-2.0.4-56 mod in my server. Some players said they can use "Sacrificial Dagger" before they login. "Sacrificial Dagger" is used to reduce the health of owner to save as energy. 
In addition, has this bug, https://github.com/SpongePowered/SpongeCommon/issues/528, been fixed in latest sponge?

**Comment by games647** [comment]
Just try it out.

**Comment by 5igm** [comment]
Thank you very much.

**Comment by 5igm** [comment]
The problem still exists.
https://my.pcloud.com/publink/show?code=XZsTWWZQ3JTnXviuybi2i8H3UcTXHhBxzwX

**Comment by 5igm** [comment]
Do you still notice here? @games647

**Comment by games647** [comment]
That's not a Flexible Login issue

**Comment by 5igm** [comment]
Should I report this to spongeforge?

**Comment by games647** [comment]
Yes

**Comment by hunter688** [comment]
I think this issue should be opened. If you cannot deny drop items before player authorized you should save inventory when player disconnected, then load when player succesfully logged and authorized.

**Comment by games647** [comment]
@hunter688 
>I think not a sponge problem.

I think it is, if there is an event for it and you cancel it, but the item will be still removed from the inventory. (and it's not only client side.)
