### ISSUE TITLE
Can not support PermissionsEx?...

### ISSUE THREAD

**Issue by SourcePowered** [games647/FlexibleLogin#37]
For example, when use this command:

`/pex group defualt permission flexiblelogin.command.logout false`

Users always can logout..........

**Comment by games647** [comment]
Do you activated player permissions?

**Comment by SourcePowered** [comment]
Oh ! This is my fault !!! Sorry...
But, a player in a state that is already logged in, then he uses the /login command again, why is it still prompted "Logged  in"? I think it should be prompt: **Please do not repeat the login.** :P
