### ISSUE TITLE
The administrator and moderators to always enter a password!

### ISSUE THREAD

**Issue by ziceptor** [games647/FlexibleLogin#43]
ipAutoLogin=true
Is it possible to make a list of users who always need to enter a password to log on to the server? Like a black list.

**Comment by games647** [comment]
I added a permission to do that. I think it's more flexible. The permission is:

    flexiblelogin.no_auto_login

**Comment by ziceptor** [comment]
You are right! Thank you very much!

**Comment by ziceptor** [comment]
When it will be released?

**Comment by games647** [comment]
Here is the version for Sponge 6.X

https://github.com/games647/FlexibleLogin/releases/tag/0.12
