### ISSUE TITLE
Item dupe

### ISSUE THREAD

**Issue by sklll** [games647/FlexibleLogin#46]
Hello!
Not sure if is known bug, but one can dupe almost everything.
you can check this video: https://www.dropbox.com/s/jjzop7dx8wczhsr/2.avi?dl=0

0) You should be logged in to the system;
1) Put single item to quickbar cell;
2) Drop this item (Q or ctrl+Q);
3) Log out;
4) Open inventory and click on cell where your item was before drop.

expected: nothing happens, cell should be empty
actual: item duplicate to your inventory

5) login and pick up items dropped on step 2.

**Comment by games647** [comment]
Bug in Sponge, FlexibleLogin just cancels the drop event.

**Comment by games647** [comment]
Can you reproduce it without FastLogin, because you are logged in at that time.

**Comment by sklll** [comment]
Reproduce it without FastLogin?
you mean with another auth plugin?
or is there default auth mechanism in sponge\forge with /login and /logout commands?

The thing is that a player can dupe his items (just check the video), and case requires logging out.

**Comment by games647** [comment]
Just without FlexibleLogin

**Comment by sklll** [comment]
Hmmm?
How you suggest to reproduce it without logout command?

There is list of steps in the initial post, ALL of the steps ARE important to reproduce the bug.
You just can't repeat the scenario without the step 3:
3. Log out;

in case you are asking if steps 1-2-4 would lead to this bug - the answer is No (no matter if the pluggin installed or not)

**Comment by sklll** [comment]
It seems plugin tries to cancel drop event which happened before the logout or something.

**Comment by sklll** [comment]
3. Log out; means:
open the chat, type "/logout" (without quotes) and press enter key

**Comment by sklll** [comment]
In case it's a sponge bug - pls point where it's proper to post it

**Comment by games647** [comment]
What's your sponge version?

**Comment by sklll** [comment]
SpongeAPI: 5.1.0-snapshot-e221622
SpongeForge: 1.10.2-2171-5.1.0-BETA-2010

**Comment by games647** [comment]
I'm sorry, but I cannot reproduce it with FlexibleLogin v0.5 and the latest sponge and forge version for 1.10.2

**Comment by sklll** [comment]
I'm using the latest version from here: https://github.com/games647/FlexibleLogin/releases
which is: FlexibleLogin v0.12 for Sponge 6.X
Strangely ingame it said v 0.8

**Comment by games647** [comment]
Just a wrong version string, but please read the release title carefully. 

>Sponge 6.X

**Comment by sklll** [comment]
my bad, let me check the previous version for Sponge 5.X

**Comment by sklll** [comment]
still can be reproduced for 5.X version

**Comment by sklll** [comment]
Another issue is that I can't manage permissions for FlexibleLogin.
Which I need to fix initial problem (by disabling logout command).
I'm using PermissionManager v.2.6.0 and it manages perms for vanila commands like /pm and other mods like FoxCore and others without problems.
When it comes to FlexibleLogin - I can't deny any perms ((
Commands like 
/pm users UserName deny permission flexiblelogin.*
/pm users UserName deny permission flexiblelogin.command.logout
take no effect, user is able to logout and login and use other FlexibleLogin commands.

**Comment by games647** [comment]
You have to enable permissions in the configuration.  Please try the item buf again without other mods.

**Comment by sklll** [comment]
Checked on server with required mods (I believe are default and required): https://www.dropbox.com/s/005r59ykw6bhb86/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202017-01-28%2023.09.19.png?dl=0

Still can be reproduced 100% on my system. 
In case there are any logs or any other info that may help - just name it. Also we can do screenshare via skype or something if needed.

Thanks for the hint with enabling perms in config.

**Comment by games647** [comment]
I think sponge is conflicting with one of your mods. I just tried it with a plain forge setup with only FlexibleLogin and Sponge installed.
