### ISSUE TITLE
Imporove EMAIL_REGEX

### ISSUE THREAD

**Issue by duhast** [games647/FlexibleLogin#48]
Hello @games647 !
Can you please update `EMAIL_REGEX` [here](https://github.com/games647/FlexibleLogin/blob/67c0b57/src/main/java/com/github/games647/flexiblelogin/commands/SetEmailCommand.java#L42) to allow emails like dude@chaps.net.ua (2nd and 3rd level domains) ?

---

Also is there any reason for not allowing lowercase characters?

**Comment by games647** [comment]
https://github.com/games647/FlexibleLogin/commit/e4c9976d199fcedd960a98e8720fa0211cb99ee9

>Also is there any reason for not allowing lowercase characters?

Yeah I noticed. I just copied it from somewhere. That was really stupid.

**Comment by duhast** [comment]
Thanks! :beer:
