### ISSUE TITLE
AuthMe compatibility

### ISSUE THREAD

**Issue by ArcasCZ** [games647/FlexibleLogin#49]
Hello,

Can I ask you about AuthMe DB compatibility? I want to run new server on SpongeForge for 1.10.2, but I have to use AuthMe 'cause of web login connected with game. And on other servers I can't run Sponge.

**Comment by evernife** [comment]
Thats something i would really like!

**Comment by games647** [comment]
I looked into it and AuthMe has many fields. We can ignore a lot of them like the last position, but it lacks of one essential field (UUID). FlexibleLogin performs all queries over the UUID instead of the player name.

**Comment by ArcasCZ** [comment]
I think there is no problem to add UUID field when user sets AuthMe compatibility to true?

**Comment by games647** [comment]
Yes, but AuthMe doesn't use this field. This means FlexibleLogin cannot find accounts registered by AuthMe, because the field will be empty.

**Comment by ArcasCZ** [comment]
I think there is no problem to do some compatibility fixes, like one condition in config which will enable - find by UUID, if not exists find by name, if not exists - register.
