### ISSUE TITLE
textConfiguration is not complete

### ISSUE THREAD

**Issue by jiangming1399** [games647/FlexibleLogin#5]
I can't change the text string "logged in" and string "Type /register or /login to login in" on the textConfiguration

**Comment by games647** [comment]
@frogocomics do you want to it?

**Comment by jiangming1399** [comment]
yes, I am a chinese so I want to change it to chinese.

**Comment by frogocomics** [comment]
@jiangming1399, how about you implement the Chinese part, then I could finish the textconfiguration for English?

**Comment by frogocomics** [comment]
@games647 Could you try to find what parts are missing from the TextConfiguration

**Comment by games647** [comment]
@frogocomics I think the tasks folder and the PlayerListener is uncovered.

Thanks for doing it.
