### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by ziceptor** [games647/FlexibleLogin#51]
A message appears on successful login. You can play, run commands... But after a few seconds automatically exit and the message that the time for entry has expired.

timeoutLogin=50

**Comment by games647** [comment]
>But after a few seconds automatically exit and the message that the time for entry has expired.

So you get kicked?

**Comment by ziceptor** [comment]
Yes. After a timeout.

**Comment by games647** [comment]
Which version do you use?
