### ISSUE TITLE
Server crashing on failed user login

### ISSUE THREAD

**Issue by AsylumDreams** [games647/FlexibleLogin#54]
Running:
Flexible Login 12.3
Sponge API: 5.1.0 Snapshot 6459642   
SpongeForge 1.10.2-2221-5.1.0 Beta 2142   
MinecraftForge 12.18.3.2221

Config:

bypassPermission=false
commandOnlyProtection=false
emailConfiguration {
    account=""
    enabled=false
    host="smtp.gmail.com"
    password=""
    port=465
    senderName="Your minecraft server name"
    subject="Your new Password"
    text="New password for %player% on Minecraft server %server%: %password%"
}
hashAlgo=bcrypt
ipAutoLogin=false
lockCommand=""
maxAttempts=5
maxIpReg=10
minPasswordLength=4
playerPermissions=false
protectedCommands=[
    op,
    pex
]
safeLocation=false
sqlConfiguration {
    database=flexiblelogin
    password=""
    path="%DIR%"
    port=3306
    type=H2
    useSSL=false
    username=""
}
teleportConfig {
    coordX=-626
    coordY=11
    coordZ=760
    defaultSpawn=false
    enabled=true
    worldName=""
}
timeoutLogin=60
updateLoginStatus=false
waitTime=300

**Comment by games647** [comment]
Server log?

**Comment by AsylumDreams** [comment]
Oops. Sorry, Stack trace below

http://pastebin.com/NQDJwyfb

**Comment by games647** [comment]
This looks like an issue from another plugin:
>ClassNotFoundException: com.sk89q.worldedit.forge.ForgeWorldEdit

**Comment by AsylumDreams** [comment]
Hmm.
 Yep. That seems to be it :/
  Would never have imagined WE would cause any kind of conflict with you o_0

 Will have a nose around with them. Thanks muchly.
