### ISSUE TITLE
FlexibleLogin Ignores Bypass Permission in LuckPerms

### ISSUE THREAD

**Issue by john01dav** [games647/FlexibleLogin#55]
Hello,

I am using FlexibleLogin with LuckPerms on Sponge with the FTB Infinity modpack. When I give my users the flexiblelogin.bypass permission, although they are not spammed with the /register message, they still get kicked after the login timeout. I would like to only require staff members to /register and to disable it for regular users.

Screenshot of default group's permissions:
![screenshot from 2017-03-21 11-55-44](https://cloud.githubusercontent.com/assets/3982497/24159561/5f5410cc-0e2d-11e7-81a1-3232cf3b4bde.png)

Versions:
Luckperms: v3.0.41
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
SpongeForge: 1.10.2-2254-5.2.0-BETA-2230
Minecraft Forge: 12.18.3.2254
FlexibleLogin: 0.12.3

**Comment by games647** [comment]
Do you activated the bypass permission in the config?

**Comment by john01dav** [comment]
I have playerPermissions and bypassPermission set to true.

**Comment by john01dav** [comment]
Here's my full config: http://pastebin.com/E9yu7sGS
