### ISSUE TITLE
Conflit between FlexibleLogin and CustomNpc mod 

### ISSUE THREAD

**Issue by Flashback083** [games647/FlexibleLogin#56]
Hello ! Yeah its very weird bug but i don't know why.
I explain : I use CustomNpc mod in my server (with FlexibleLogin of  course) and i create somes script to interact with my npc.
Exemple of script : 
function interact(event){
event.npc.say("test!!!!");
}
This script make npc say "test!!!" in chat when we interact with him.
But the script dont work if your plugin is enable on server !
I remove this plugin and its work again. I very dont know how to fix it but its very horrible >w<
Do you have any idea why i have this bug ?
I run my server in 1.10.2, and 0.12.3 of your plugin (bug with all version)
Thanks to read, tell me if you need another information.
Thanks.

**Comment by Flashback083** [comment]
I have somes info, also its your  @Listener
    public void onChat(MessageChannelEvent.Chat chatEvent, @First Player player) {
        checkLoginStatus(chatEvent, player);
} who make the bug

**Comment by games647** [comment]
I tried it. It should work now. I guess it's fixed by the Sponge team.
