### ISSUE TITLE
TOTP Name

### ISSUE THREAD

**Issue by Magi1053** [games647/FlexibleLogin#58]
I noticed that the name of the TOTP is in my case `Magi1053@localhost.localdomain`. Is there any way to change this to be my server's hostname?

**Comment by games647** [comment]
It's the server bound-address inside the server properties

**Comment by Magi1053** [comment]
You are talking about the server-ip property? You can't put a hostname into that field.

Could you add an option in the config to override the hostname?

**Comment by Magi1053** [comment]
You were referring to the system host file.
