### ISSUE TITLE
Database console spam and error

### ISSUE THREAD

**Issue by KappaKiddie** [games647/FlexibleLogin#62]
Error spam: https://pastebin.com/HmJ5buQn

Full server log ( there's another error spamming the entire log, idk if was caused by this error, but if anyone could check it for me too ): https://www.dropbox.com/s/ywycgpc0m1dx9je/fml-server-latest.log?dl=0 ( There's a HUGE log file, 150mb )

**Comment by games647** [comment]
Plesse look at the logging level. It's debug so nothing to worry about. But 150mb is really a lot. So it would better to disable those messages.

**Comment by KappaKiddie** [comment]
How I do this?

**Comment by games647** [comment]
Post this on the sponge forum. HikariCP is added in sponge directly, so they should handle that.
