### ISSUE TITLE
[Suggestion] Cancel chat event before login

### ISSUE THREAD

**Issue by KappaKiddie** [games647/FlexibleLogin#63]
My users are sending they pass before login, when forgot to use /, please fix this

**Comment by games647** [comment]
I already cancel the chat event. Do you use the correct version?

**Comment by kaal-1** [comment]
It seems like it is cancelling commands only.
When I enter the server and type something in chat (before logging in) it is sent. Last sponge and plugin version.

**Comment by games647** [comment]
What Minecraft version do you use? 
What Sponge and FlexibleLogin version and do you tried? 
Could you verify that this message is also visible to others not just the sender? 
Could you try it again without any other plugins. This is what I tried

Do you use SpongeForge or SpongeVanilla?

**Comment by kaal-1** [comment]
SpongeForge 2281-5.2.0-BETA-2422
Minecraft 1.10.2
Flexible Login v0.13

Yes everybody can see the text, it is even sent to discord (discordintegration mod).
I'll test without any other plugins...

**Comment by games647** [comment]
Well you are using the wrong version of FlexibleLogin. FlexibleLogin is only for:
>Update to Sponge 7.0 (Minecraft 1.12) Fixes # 64

and previous builds from >0.12 are for 6.0

**Comment by kaal-1** [comment]
So API 5 (minecraft 1.10.2) support was dropped completely?

**Comment by games647** [comment]
You could still use an older version.
