### ISSUE TITLE
Signed up for abc, ABC can also register for the game

### ISSUE THREAD

**Issue by qijidaren** [games647/FlexibleLogin#66]
Signed up for abc, ABC can also register for the game

**Comment by qijidaren** [comment]
ABC can log in

**Comment by qijidaren** [comment]
ABC online, abc can't go game

**Comment by games647** [comment]
So should both accounts be playable?

**Comment by qijidaren** [comment]
yes

**Comment by qijidaren** [comment]
ABC online ,  abc can't play games.

**Comment by qijidaren** [comment]
What do I do

**Comment by qijidaren** [comment]
Do you understand my consciousness?

**Comment by games647** [comment]
I fixed it already

**Comment by qijidaren** [comment]
I want to ，register for aaa, can't register AAA

**Comment by games647** [comment]
I asked you:
>So should both accounts be playable?

and you said yes

**Comment by qijidaren** [comment]
Will go wrong

**Comment by qijidaren** [comment]
There are more problems

**Comment by qijidaren** [comment]
Thank you for
