### ISSUE TITLE
(Game game, Logger logger) method in constructors of classes is no longer needed

### ISSUE THREAD

**Issue by frogocomics** [games647/FlexibleLogin#7]
In my latest pull request #6 I added a safe getInstance() method in the main plugin class, which allows you to easily get an instance of Game and Logger. Because of this, the Game and Logger parameters in the constructor of most classes are no longer required.

(You also removed the getInstance() method I created, I want it back)

**Comment by games647** [comment]
> I want it back

Why, in my opinion static variables leads to memory leaks?

**Comment by frogocomics** [comment]
It would not lead to memory leaks, as noticed how the instance of the plugin class was passed during the InitializationEvent. Plus, you can trust me: the Sponge devs suggested it in irc.

**Comment by frogocomics** [comment]
Also, Sponge.getGame() can also be used.

**Comment by games647** [comment]
>Also, Sponge.getGame() can also be used.

Because Sponge is always available if the server is running.

>It would not lead to memory leaks, as noticed how the instance of the plugin class was passed during the InitializationEvent. Plus, you can trust me: the Sponge devs suggested it in irc.

Then I might be wrong. I'll add it.
