### ISSUE TITLE
Can't register when using jbcrypt

### ISSUE THREAD

**Issue by aotsishd** [games647/FlexibleLogin#70]
Using a server with the following specs:
Minecraft version: 1.10.2
Forge version: 12.18.3.2281
Sponge version: 5.2.0-BETA-2464
FlexibleLogin version: 0.14.4

Tried to register a user while using a H2 DB and jbcrypt as the hashing method, however, after typing "/register pass pass", nothing is shown on the client side, and the register notice keeps popping until the user times out and gets kicked off the server. The server console showed this output whenever a user tried to register:
[https://pastebin.com/N04s7Q7n](url)

I supposed it could be because FlexibleLogin was built for the 7.x Sponge API, so I tried using FlexibleLogin on a 1.12 server (using latest Forge and SpongeForge versions) and no other mods/plugins other than Sponge and FlexibleLogin, but I got the same output log.

**Comment by games647** [comment]
Fixed with the last commit.
