### ISSUE TITLE
Pixelmon inventory support

### ISSUE THREAD

**Issue by evernife** [games647/FlexibleLogin#74]
Actually people can edit the pokemons before login, like removings it's abilities

**Comment by games647** [comment]
I'm not really familiar with pixelmon, so I don't know what you mean with abilities, could you please explain what they are.

Actually the plugin cancels all change inventory events that Sponge provides. Could you post what Sponge version and Plugin version do you use, maybe it's an issue with an incompatible version? Could you also post how you edit the pokemons, maybe they trigger a different event?

**Comment by evernife** [comment]
Step by step

1- Join server, open inventory:

![image](https://user-images.githubusercontent.com/11357801/30510120-94f9799e-9a94-11e7-900d-fae77c2be784.png)

2- Righ click on one of the pokemon slots:

![image](https://user-images.githubusercontent.com/11357801/30510127-b87df5b6-9a94-11e7-93fc-923b9e3eefa7.png)

3- Then just select a stats and click on the trash:

![image](https://user-images.githubusercontent.com/11357801/30510134-d255dada-9a94-11e7-9cd9-bf798d736982.png)

I asked for suport because its an aditional menu, and i know the defaults wouldnt handle that.

-------

Forge: `forge-1.10.2-12.18.3.2422-universal.jar`
Sponge: `spongeforge-1.10.2-2281-5.2.0-BETA-2610.jar`
ThePlugin: `flexiblelogin-0.14.7.jar`

**Comment by games647** [comment]
It could because you use an outdated Sponge version.

**Comment by evernife** [comment]
Tried with `spongeforge-1.10.2-2477-5.2.0-BETA-2637.jar`

Same problem :D 

![image](https://user-images.githubusercontent.com/11357801/30510447-8f2df5d4-9a9a-11e7-93cc-98c345c7a391.png)

**Comment by games647** [comment]
What happens after a relogin, does it reset or does it keep the changes?

**Comment by evernife** [comment]
Keep changes

**Comment by games647** [comment]
Could you try the newest version of FlexibleLogin.

https://github.com/games647/FlexibleLogin/blob/144c41b6d28b9d0ddb4b1824d129702457edb048/CHANGELOG.md#L213-L223

**Comment by evernife** [comment]
Yes, it solves the inventory problem!

There is another one related to pixelmon, i will open a new issue as soon as i make a few tests!
