### ISSUE TITLE
Items on left hand still can right-click

### ISSUE THREAD

**Issue by evernife** [games647/FlexibleLogin#75]
![image](https://user-images.githubusercontent.com/11357801/30510930-9a80f76a-9aa4-11e7-80dc-8fbdc54be761.png)

In the exemple, i press "F" to change the gold shovel from the hotbar to the left hand, and then i can right-click on blocks to create a claim.

**Comment by evernife** [comment]
Now that i make a few tets, even in hotbar they can still be used

**Comment by games647** [comment]
I tried it should already be cancelled, what plugin do you use for this message, maybe it's listening to the wrong priority?

**Comment by evernife** [comment]
[Sponge Grief Prevention](https://forums.spongepowered.org/t/griefprevention-official-thread-1-10-1-11-1-12-town-wecui-support/1123) [(Github)](https://github.com/MinecraftPortCentral/GriefPrevention)

**Comment by games647** [comment]
Does it also happen if you have it on the main hand?

**Comment by evernife** [comment]
yes
