### ISSUE TITLE
Bungeecord Forced Host

### ISSUE THREAD

**Issue by kaal-1** [games647/FlexibleLogin#79]
I'm using the plugin on a 1.10.2 sponge server with bungeecord forced host and UltimateChat.
It works fine until I login, then no chat messages or command are sent to the server. No error is shown in the console either.

Minecraft Forge 2477
SpongeForge 1.10.2-2477-5.2.0-BETA-2637 
FlexibleLogin v0.14.6 for Sponge 5

**Comment by games647** [comment]
I could try to build a debug version for you where it makes logging every time a chat or command event triggers.

**Comment by kaal-1** [comment]
I could try that, but I don't think it is triggering it actually, maybe it's a problem with bungeecord or a specific problem with bungee + flexiblelogin, since it started when I installed it.

If I connect to my hub server then use /server sponge the chat works, but if I connect directly to it via the forced host, it doesn't.
I don't know bungee very well, but maybe some kind of packet is not being sent? lol I'm confused.

**Comment by games647** [comment]
Could you try this out: https://github.com/games647/FlexibleLogin/releases/tag/0.14.7-testing

**Comment by games647** [comment]
@kaal-1 Any news?
