### ISSUE TITLE
Migrate H2 -> mysql

### ISSUE THREAD

**Issue by evernife** [games647/FlexibleLogin#80]
Is there any way to change the type of databases, from H2 to MySQL ? A way to convert it ?

**Comment by games647** [comment]
1. Create the MySQL table either with FlexibleLogin or directly using this SQL script from your terminal or PHPMyAdmin interface:

```sql
CREATE TABLE flexiblelogin_users (
  `UserID`    INTEGER PRIMARY KEY AUTO_INCREMENT,
  `UUID`      BINARY(16)  NOT NULL,
  `Username`  VARCHAR,
  `Password`  VARCHAR(64) NOT NULL,
  `IP`        BINARY(32)  NOT NULL,
  `LastLogin` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Email`     VARCHAR(64)          DEFAULT NULL,
  `LoggedIn`  BOOLEAN              DEFAULT 0,
  UNIQUE (`UUID`)
)
```
2. Download the h2 driver from here: https://h2database.com/html/download.html
3. Run this from the same folder as the download jar file 
`java -cp DOWNLOADED_DRIVER.jar org.h2.tools.Script -url jdbc:h2:///home/XXX/.../Sponge-Server/config/flexiblelogin/database`
4. Run the INSERT INTO statements from the generated file in MySQL, but you should remove the public.flexiblelogin_users to flexiblelogin_users(....

**Comment by evernife** [comment]
Ty, i will try :D

**Comment by DarkBlade177** [comment]
Can't you add a more easy-way to do this, like the luck perms command to export than import?

For newbies like me its almost impossibe, and i use a panel host, i cant install things T.T

**Comment by games647** [comment]
You can also copy it to your local host, but as you already said it's not easy.
