### ISSUE TITLE
Plugin don't work corectly

### ISSUE THREAD

**Issue by WareZ57** [games647/FlexibleLogin#82]
Hello I use the plugin recently but this one has problems when someone logs on he can use the inventory and all that follows and even if he did not enter the password if he can use the account ...

Lasted sponge build 1.11.2 & lasted forge in 1.11.2

(Sorry bad english) :fr: 

Look : https://youtu.be/nmHinkxV1TM 🎦

**Comment by games647** [comment]
I need the server log and the plugin version

**Comment by WareZ57** [comment]
0.15.4 and logs : https://pastebin.com/bbaCeVen

**Comment by games647** [comment]
Please try out 0.15 first. It's explicitly for Sponge 6.0. Second that's not the complete server log. There is a lot missing like if FlexibleLogin is actually loaded.

**Comment by WareZ57** [comment]
Hello i have talk To other user using your plugin ans he say add griefpreviention api now the plugin Work at 98% all work good but you can drop item in hands. 

I give correct logs after my work thx

**Comment by games647** [comment]
GriefPrevention support was already added for Sponge 7 and item drops should already be prevented.

**Comment by WareZ57** [comment]
Last bug : https://youtu.be/TqGKhHkv4Lc

Logs : http://pastebin.fr/52044

**Comment by games647** [comment]
Please try out 0.15 and tell me what doesn't work.

**Comment by WareZ57** [comment]
Work fine now !
