### ISSUE TITLE
Account already exists

### ISSUE THREAD

**Issue by Bannan123** [games647/FlexibleLogin#83]
Hey, i've downloaded your plugin but i can't make it work, everytime i login into a game after registration im getting error "Account already exists and i have no idea why is that, i think i can't connect to DB ? probably beacuse i can't see any changes in my MYSQL, 

# Database configuration
sqlConfiguration {
    # Database name
    database="sdb_10987"
    # Password in order to login
    password=aaaaaaaa
    # Path where the database is located. This can be a file path (h2/SQLite) or an IP/Domain(MySQL)
    path="***.***.**.***"
    # Port for example MySQL connections
    port=3306
    # SQL server type. You can choose between h2, SQLite and MySQL
    type=MYSQL
    # It's strongly recommended to enable SSL and setup a SSL certificate if the MySQL server isn't running on the same machine
    useSSL=false
    # Username to login the database system
    username="sdb_10987"

there's my db configuration can you tell me if something is wrong here? didn't change probably anything else. Thanks !

**Comment by Bannan123** [comment]
im using :
flexiblelogin-0.15.4
forge-1.10.2-12.18.3.2477-installer
spongeforge-1.10.2-2477-5.2.0-BETA-2698
SpongeBootstrap-0.2.0
FTBPresentsSkyfactory3Server_3.0.15 < server files.

**Comment by games647** [comment]
Please post your server log.

**Comment by Bannan123** [comment]
[fml-server-3 (1).log](https://github.com/games647/FlexibleLogin/files/1430088/fml-server-3.1.log)
[fml-server-latest (1).log](https://github.com/games647/FlexibleLogin/files/1430089/fml-server-latest.1.log)
 Don't know which one i should upload but they're pretty much the same. Thanks alot !

**Comment by games647** [comment]
>java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `Password` VARCHAR(64) NOT NULL , `IP` BINARY(32) NOT NULL , `LastLogin` TIMEST' at line 1

Could you please try 0.16?

**Comment by Bannan123** [comment]
i have to change config file or i can leave the previous one ?

**Comment by games647** [comment]
You can keep it.

**Comment by games647** [comment]
Using the new version?

**Comment by Bannan123** [comment]
![123](https://user-images.githubusercontent.com/33242254/32224981-c1f25696-be43-11e7-876f-5819f0bcc5b8.JPG)
It shouldn't save accounts into my database? or it's just creating local file inside config folder?

**Comment by Bannan123** [comment]
yes 0.16

**Comment by games647** [comment]
If you use a new config. Then it uses H2 by default.

**Comment by Bannan123** [comment]
Ye but i've edited it.
`sqlConfiguration {
    # Database name
    database=sdb_10987
    # Password in order to login
    password="aaaaa"
    # Path where the database is located. This can be a file path (h2/SQLite) or an IP/Domain (MySQL/MariaDB)
    path="1aaaaa"
    # Port for example MySQL connections
    port=3306
    # SQL server type. You can choose between h2, SQLite and MySQL/MariaDB
    type=MYSQL
    # It's strongly recommended to enable SSL and setup a SSL certificate if the MySQL/MariaDB server isn't running on the same machine
    useSSL=false
    # Username to login the database system
    username="sdb_10987"
`

**Comment by games647** [comment]
Then please send me your log again.

**Comment by Bannan123** [comment]
Just restarted server, got same thing again, i think it's just problem with my db.

**Comment by games647** [comment]
Just send me the log.

**Comment by Bannan123** [comment]
[fml-server-3.log](https://github.com/games647/FlexibleLogin/files/1430827/fml-server-3.log)
i think it's this one.

**Comment by games647** [comment]
Please try out 0.16.1

**Comment by Bannan123** [comment]
It's using config from 0.16?

**Comment by games647** [comment]
Yes always

**Comment by Bannan123** [comment]
hmm i should type password ip's etc. between "" ?

**Comment by games647** [comment]
Yes the host address in path.

**Comment by Bannan123** [comment]
![123](https://user-images.githubusercontent.com/33242254/32227155-cedcb6ce-be4a-11e7-999b-0262bbeeb9c8.JPG)
I think it's fixed ! :)

**Comment by Bannan123** [comment]
Hey got 1 more question, is there any protection before login? beacuse i can see that u can run around and do everything before you got kick.

**Comment by games647** [comment]
It will prevent that stuff, but you have to use the correct plugin version for your running sponge api.

**Comment by Bannan123** [comment]
I've just started with minecraft servers and sponge so dont rly know much.
Sponge Api u mean i have to download other than spongeforge? now using only these 2.
spongeforge-1.10.2-2477-5.2.0-BETA-2698
SpongeBootstrap-0.2.0
i have these 2 atm. and turning on server by spongebootstrap

**Comment by games647** [comment]
In your case the Sponge API is 5.2.0. The latest version of Flexible compiles against 6.0. I uploaded a new version that should work with 5.1 and up.

**Comment by Bannan123** [comment]
Thanks, but still can mess with commands and blocks while not logged in.
