### ISSUE TITLE
Can use commands / place blocks before login 

### ISSUE THREAD

**Issue by Bannan123** [games647/FlexibleLogin#84]
Hey, don't know if u're still previous topic, so i've downloaded version for 5.2 sponge but still can do everything before login.

**Comment by games647** [comment]
Do you tried the -sponge5 version like I said?

**Comment by Bannan123** [comment]
flexiblelogin-0.16.1-sponge5 this one? yes i did

**Comment by Bannan123** [comment]
[flexibleloginpl.txt](https://github.com/games647/FlexibleLogin/files/1432539/flexibleloginpl.txt)
Hey there you have "config" file translated to polish, tomorrow i'll translate messages.conf probably :)
(.txt file beacuse github doesnt let me to upload config file.)

**Comment by games647** [comment]
Please try the latest uploaded version.

**Comment by Bannan123** [comment]
Yup it works ! :D Thanks alot !
