### ISSUE TITLE
Can't add new TOTP to Google Authenticator.

### ISSUE THREAD

**Issue by john01dav** [games647/FlexibleLogin#87]
Hello,

I am currently trying to get this plugin working to secure staff accounts on my server. I have run into an issue, however: I can't add the code to my Android phone's Google Authenticator. Specifically, when I attempt to use the QR code method, it gives me an error saying "key not recognized" and when I attempt to use the manual key entry, it complains of illegal characters (specifically, any non-letter or = characters). How can I correctly set this up on my server?

Thank you.

Google Authenticator version: 5.0.0
FlexibleLogin version: 0.16.3

**Comment by games647** [comment]
It looks like they are currently not compatible with HmacSHA512. I downgraded to HmacSHA256 for now.

**Comment by john01dav** [comment]
I just downloaded version 0.16.3 and tried it, and this time I still have the "key not regonized" error with the QR code, but when entering the textual code manually I get a "Key value is too short" error.

Is there some other TOTP app I can use to make this work more reliably?

**Comment by games647** [comment]
Could you try it with FreeOTP?

**Comment by john01dav** [comment]
I tried it with that app as well right after I made my last comment. It failed. It said the QR code was invalid (I don't remember the exact message, but I can get that if necessary) and gave numbers the plugin rejected when I attempted to manually enter the numbers (with 6 digits, SHA256 settings).

**Comment by games647** [comment]
I found out that I uploaded the wrong jar. A new one is uploaded
