### ISSUE TITLE
Nickname case-sensitive check

### ISSUE THREAD

**Issue by evernife** [games647/FlexibleLogin#88]
Example:

A nick `EverNife` joins the server today.
Tomorrow  player called `everNIFE` try to join and he is told that the nick already exists.

This should be usefull to prevent frauds! ( i am having this problem on my network T.T)

**Comment by evernife** [comment]
Plugin: flexiblelogin-0.16.3.jar
Sponge: spongeforge-1.10.2-2477-5.2.0-BETA-2691.jar

**Comment by games647** [comment]
What's your storage type? SQLite, MySQL or H2?

**Comment by games647** [comment]
It should verify that on register.

**Comment by evernife** [comment]
So there is no bug, i was thinking it should prevent the player from joining the server.

The problem of not preventing the first join is that you screll up with "tab complete" for offline players.

When i use the tab complete for "ever" i get "EverNife", "EverNIFE", "EverNiFe".

So, could you change the time when the check is made ?
