### ISSUE TITLE
Drop event not being canceled

### ISSUE THREAD

**Issue by evernife** [games647/FlexibleLogin#95]
I can drop items even when not logged in

![2018-01-02_05 15 21](https://user-images.githubusercontent.com/11357801/34476889-f66efa14-ef7b-11e7-9473-2c88c399cae8.png)

Minecraft: `1.10.2`
Sponge: `spongeforge-1.10.2-2477-5.2.0-BETA-2777.jar`
FlexibleLogin: `flexiblelogin-0.16.7.jar`

Maybe related to this 
![image](https://user-images.githubusercontent.com/11357801/34476995-f0c49db6-ef7c-11e7-942f-b3f6ebd5e77e.png)

**Comment by games647** [comment]
The Plugin doesn't listen to pre order it subscribes to first.

**Comment by games647** [comment]
Is this still relevant?

**Comment by evernife** [comment]
Sorry, seems to be working fine now! 

I will make a few more tests to be sure.
