### ISSUE TITLE
Entrance without registration

### ISSUE THREAD

**Issue by ziceptor** [games647/FlexibleLogin#96]
With these settings, the player can log in without registering. Also on behalf of another player.

**permissions**

```
  "permissions": [
    "flexiblelogin.bypass",
    "flexiblelogin.command.changepw",
    "flexiblelogin.command.login",
    "flexiblelogin.command.logout",
    "flexiblelogin.command.register",
    {
      "flexiblelogin.no_auto_login": {
        "value": false
      }
    },
```

**config**

```
# Do you allow your users to skip authentication with the bypass permission
bypassPermission=true
ipAutoLogin=false
playerPermissions=true
```

**Comment by games647** [comment]
Therefore the bypass permission exists.

**Comment by ziceptor** [comment]
How to configure for registration, but bypass only /log

**Comment by games647** [comment]
Could provide an example for a use case?

**Comment by ziceptor** [comment]
A new player must register. And to log in /log once. After should automatically connect.

**Comment by games647** [comment]
But why should the player then register in the first place?

**Comment by ziceptor** [comment]
Not sure I understand the question.

**Comment by ziceptor** [comment]
ipAutoLogin=true
How does it work?

**Comment by games647** [comment]
Why should players register and then don't have to login?

IpAutoLogin will automatically login players if they come from the same IP-address within a 24 hour time frame.

**Comment by ziceptor** [comment]
Thank You! I just forgot about it. 've already set up. Works.
