### ISSUE TITLE
Item duplication bug 

### ISSUE THREAD

**Issue by nzgs** [games647/FlexibleLogin#97]
Minecraft: 1.12.2
Sponge: spongevanilla-1.12.2-7.1.0-BETA-16.jar
FlexibleLogin: flexiblelogin-0.16.8.jar

![screenshot_20180211_18_37_1](https://user-images.githubusercontent.com/36361861/36071962-bb3f87fc-0f5a-11e8-9269-0ce00c314fc6.png)

![screenshot_20180211_18_39_2](https://user-images.githubusercontent.com/36361861/36071972-efcafefc-0f5a-11e8-89fc-05b298988f42.png)
when player is not logged in and there are items in both hands, **pressing F key(off-hand swap)** causes item duplication.

![screenshot_20180211_18_40_3](https://user-images.githubusercontent.com/36361861/36071989-1ed9ae1e-0f5b-11e8-9ae5-b79aaabea4ae.png)
![screenshot_20180211_18_41_4](https://user-images.githubusercontent.com/36361861/36071999-4519b7ea-0f5b-11e8-9ab5-f4c45d11c11b.png)
(as you can see, dark oak wood is duplicated)

this also happens on forge-modded sponge server.

**Comment by games647** [comment]
Does the item still exist after relogin

**Comment by nzgs** [comment]
yes item still exists after relogin

**Comment by games647** [comment]
What other mods do you use?

**Comment by nzgs** [comment]
currently i'm using only optifine and xaeros minimap

i don't think that mods are causing the bug..

**Comment by nzgs** [comment]
just tested on vanila client and bug still happens

**Comment by games647** [comment]
No I meant server mods

**Comment by nzgs** [comment]
i'm only using a antixray and flexiblelogin

**Comment by games647** [comment]
With wich SpongeForce do you tried it? The Sponge community currently recommends 2900 and I need that info to for reproducing it.

**Comment by nzgs** [comment]
sorry but i have no idea what my spongeforce is X(

where can i check it?

**Comment by games647** [comment]
I meant SpongeForge, sorry the typo

**Comment by nzgs** [comment]
server i tested today was SpongeVanilla beta 16..

i saw this bug happening on server using SpongeForge, but i don't know what version of SpongeForge that server was using X(( sorry

**Comment by games647** [comment]
Could you try beta 18, because I cannot even switch the items off hand to main hand.

**Comment by nzgs** [comment]
i'll try it now

**Comment by ternsip** [comment]
Can not reproduce this bug by myself. I think either not enough details how to reproduce or bug in another mod.
