### ISSUE TITLE
Mod flexiblelogin (FlexibleLogin) requires [griefprevention@[4.3.0,)

### ISSUE THREAD

**Issue by evernife** [games647/FlexibleLogin#98]
The 1.10.2 version of GriefPrevention is 
![image](https://user-images.githubusercontent.com/11357801/36077003-bc5fd43e-0f4b-11e8-8e20-57eff257d3f3.png)

4.3.0 is only for 1.12.2

**Comment by games647** [comment]
The dependency is optional
