### ISSUE TITLE
Invalid Username Error

### ISSUE THREAD

**Issue by GershonR** [games647/FlexibleLogin#99]
I'm planning to update my server from Sponge 1.10.2 to 1.12.2, I use a pretty old version of FlexibleLogin (0.8) and when I updated to 0.16.8 I get a invalid username error, and its asking me to login with the lowercase version of my name, how do I disable this?

spongeforge-1.10.2-2477-5.2.0-BETA-2731

forge-1.12.2-14.23.2.2616-universal

**Comment by GershonR** [comment]
Thanks, are you planning on releasing a build soon so I can test?

**Comment by games647** [comment]
https://ci.codemc.org/view/Games647/job/FlexibleLogin/changes

**Comment by games647** [comment]
Always write the plugin version too.

**Comment by GershonR** [comment]
I was on flexiblelogin-0.17.1
Updated to flexiblelogin-0.17.4 and it worked, sorry about that!
